## Preparing SV Dataset

In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pylab as plt

#np.set_printoptions(formatter={'int':hex})

import os
files = os.listdir('sv_traces/')

### reads an sv_trace file into 2 structures:
### pcs: a list of 1001 16-bit pc values
### mem: a list of 1001 65542-byte memory vectors
def read_trace(sv_file):
    with open(sv_file, 'rb') as f:
        lines = f.read()
        lines = np.frombuffer(lines, dtype=np.uint8)
        lines = lines.reshape(1001,-1)
        pcs = lines[:, 0:2]
        mem = lines[:, :]
        #pcs = [np.uint16(i[1]<<8 | i[0]) for i in pcs]
        return mem, pcs
    
### reads trace data into a dataset of mem-to-pc mappings, where
### mem_current: partial memory trace &
### pcs_current: full pcs trace
def read_dataset(file):
    mem_trace = dict_traces[file][0]
    mem_current = mem_trace[:]
    pcs_trace = dict_traces[file][1]
    pcs_current = pcs_trace[:]
    return mem_current, pcs_current

### dict_traces[file][0]: memory trace of <file>
### dict_traces[file][1]: pc trace of <file>
dict_traces = {}
for file in files[0:20]:
    dict_traces[file] = read_trace(os.path.join('sv_traces/', file))
    
### dict_dataset[file][0]: memory trace of <file>
### dict_dataset[file][1]: pc trace of <file>
dict_dataset = {}
for trace in dict_traces:
    dict_dataset[trace] = read_dataset(trace)

In [2]:
dict_traces

{'167:149:9.svbinttrc': (array([[  0,   2,   0, ...,   2,   0,   0],
         [  1,   2,   0, ...,   2,   0,   0],
         [  3,   2,   0, ...,   2,   0,   0],
         ...,
         [  3,   2, 126, ...,   2,   0,   0],
         [  5,   2,  20, ...,   2,   0,   0],
         [  7,   2,  20, ...,   2,   0,   0]], dtype=uint8),
  array([[0, 2],
         [1, 2],
         [3, 2],
         ...,
         [3, 2],
         [5, 2],
         [7, 2]], dtype=uint8)),
 '121:187:13.svbinttrc': (array([[ 0,  2,  0, ...,  2,  0,  0],
         [ 1,  2,  0, ...,  2,  0,  0],
         [ 3,  2,  0, ...,  2,  0,  0],
         ...,
         [ 9,  2, 50, ...,  2,  0,  0],
         [10,  2, 50, ...,  2,  0,  0],
         [11,  2, 50, ...,  2,  0,  0]], dtype=uint8),
  array([[ 0,  2],
         [ 1,  2],
         [ 3,  2],
         ...,
         [ 9,  2],
         [10,  2],
         [11,  2]], dtype=uint8)),
 '144:101:13.svbinttrc': (array([[  0,   2,   0, ...,   2,   0,   0],
         [  1,   2,   0, ...,   2

In [3]:
dict_dataset

{'167:149:9.svbinttrc': (array([[  0,   2,   0, ...,   2,   0,   0],
         [  1,   2,   0, ...,   2,   0,   0],
         [  3,   2,   0, ...,   2,   0,   0],
         ...,
         [  3,   2, 126, ...,   2,   0,   0],
         [  5,   2,  20, ...,   2,   0,   0],
         [  7,   2,  20, ...,   2,   0,   0]], dtype=uint8),
  array([[0, 2],
         [1, 2],
         [3, 2],
         ...,
         [3, 2],
         [5, 2],
         [7, 2]], dtype=uint8)),
 '121:187:13.svbinttrc': (array([[ 0,  2,  0, ...,  2,  0,  0],
         [ 1,  2,  0, ...,  2,  0,  0],
         [ 3,  2,  0, ...,  2,  0,  0],
         ...,
         [ 9,  2, 50, ...,  2,  0,  0],
         [10,  2, 50, ...,  2,  0,  0],
         [11,  2, 50, ...,  2,  0,  0]], dtype=uint8),
  array([[ 0,  2],
         [ 1,  2],
         [ 3,  2],
         ...,
         [ 9,  2],
         [10,  2],
         [11,  2]], dtype=uint8)),
 '144:101:13.svbinttrc': (array([[  0,   2,   0, ...,   2,   0,   0],
         [  1,   2,   0, ...,   2

## Defining Neural Net

In [4]:
import torch
import torch.nn as nn
import torch.optim as optim

In [5]:
def format_label(l, width=16):
    val = bin(l)[2:]
    N = len(val)
    return [0.] * (width-N) + [float(i) for i in val]

In [6]:
format_label(512)

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0]

In [119]:
features, labels = dict_dataset[list(dict_dataset.keys())[0]]
for file in list(dict_dataset.keys())[1:10]:
    features = np.append(features, dict_dataset[file][0], axis=0)
    labels = np.append(labels, dict_dataset[file][1], axis=0)
features_test, labels_test = dict_dataset[list(dict_dataset.keys())[10]]
for file in list(dict_dataset.keys())[11:13]:
    features_test = np.append(features_test, dict_dataset[file][0], axis=0)
    labels_test = np.append(labels_test, dict_dataset[file][1], axis=0)

In [120]:
#features, labels = dict_dataset[list(dict_dataset.keys())[0]]
#features_test, labels_test = dict_dataset[list(dict_dataset.keys())[1]]
#features = features - features.mean(axis=0)
# temp
features_temp = features#[9:15, ]
labels_temp = labels#[9:15]
# end temp

In [9]:
print(labels_test[0:16])
print(labels_temp[0:16])


[[ 0  2]
 [ 1  2]
 [ 3  2]
 [ 5  2]
 [ 7  2]
 [ 8  2]
 [ 9  2]
 [10  2]
 [11  2]
 [12  2]
 [13  2]
 [14  2]
 [15  2]
 [16  2]
 [17  2]
 [18  2]]
[[ 0  2]
 [ 1  2]
 [ 3  2]
 [ 5  2]
 [ 7  2]
 [ 8  2]
 [ 9  2]
 [10  2]
 [11  2]
 [12  2]
 [13  2]
 [14  2]
 [15  2]
 [16  2]
 [ 3  2]
 [ 5  2]]


In [121]:
labels_temp[2]

array([3, 2], dtype=uint8)

In [122]:
partial_mem_trace = features_temp[: , 0:8]
#partial_mem_trace = features_temp[: , 0:1024]
features_temp = partial_mem_trace # all rows are identical here

partial_mem_trace_test = features_test[: , 0:8]
features_test = partial_mem_trace_test # all rows are identical here

    
print(partial_mem_trace.shape[0])
print(features_temp.shape[0])
print(partial_mem_trace.shape[1])
print(features_temp.shape[1])

10010
10010
8
8


In [123]:
features_temp[0]

array([ 0,  2,  0,  0,  0,  0, 20,  0], dtype=uint8)

### Training NN

In [124]:
net = nn.Sequential(
    nn.Linear(features_temp.shape[1], 2**8),
    nn.ReLU(), #rectified linear unit
    #nn.Linear(2**12, 2**10),
    #nn.ReLU(),
    #nn.Linear(2**8, 2**8),
    #nn.ReLU(),
    nn.Linear(2**8, 2),
    #nn.Sigmoid()
)

#criterion = nn.BCELoss()
#criterion = nn.CrossEntropyLoss()
criterion = nn.MSELoss()

def train(n_epochs, net, features, labels, criterion, optimizer, freq=1, debug=False):
    for i in range(n_epochs): #number of passes over full dataset
        #step 1: get features and use net to make predictions
        preds = net(torch.from_numpy(features).float())
        
        #step 2: compute loss/error
        labels_torch = torch.tensor(torch.from_numpy(np.array(labels)).float())
        if debug: print('\n------')
        if debug: print(preds)
        #loss = np.sqrt(((np.rint(preds.detach().numpy()) - labels_torch.detach().numpy())**2).mean())
        loss = criterion(preds, labels_torch)
        if i % freq == 0:
            print('epoch:', i, 'loss:', loss)

        #step 3: backprop to update weights
        # compute gradients/derivatives - backprop
        # use gradients to update weights - gradient descent - w = w - 0.1 * deriv. loss w.r.t. w

        optimizer.zero_grad() #set previous buffers to zero
        loss.backward() #backprop
        optimizer.step() #update weights        
        
    return net

optimizer = optim.Adam(net.parameters(), lr=1e-5)
print(features_temp)
#net = train(1000, net, features_temp, labels_temp, criterion, optimizer, debug=False)

[[  0   2   0 ...   0  20   0]
 [  1   2   0 ...   0  20   0]
 [  3   2   0 ...   0  22   0]
 ...
 [  5   2 145 ...   0 212   0]
 [  7   2 145 ...   0 212   0]
 [  8   2 145 ...   0 212   0]]


In [131]:
net = train(10000, net, features_temp, labels_temp, criterion, optimizer, debug=False)

/tmp/ipykernel_39771/1586916469.py:22: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels_torch = torch.tensor(torch.from_numpy(np.array(labels)).float())


epoch: 0 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 4 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 5 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 6 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 7 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 8 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 9 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 10 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 11 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 12 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 13 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 14 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 15 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 16 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 

epoch: 147 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 148 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 149 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 150 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 151 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 152 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 153 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 154 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 155 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 156 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 157 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 158 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 159 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 160 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 161 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 162 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 163 loss: tensor(0.0001, grad_fn=

epoch: 296 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 297 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 298 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 299 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 300 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 301 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 302 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 303 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 304 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 305 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 306 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 307 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 308 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 309 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 310 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 311 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 312 loss: tensor(0.0001, grad_fn=

epoch: 445 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 446 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 447 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 448 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 449 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 450 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 451 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 452 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 453 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 454 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 455 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 456 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 457 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 458 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 459 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 460 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 461 loss: tensor(0.0001, grad_fn=

epoch: 593 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 594 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 595 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 596 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 597 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 598 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 599 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 600 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 601 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 602 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 603 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 604 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 605 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 606 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 607 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 608 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 609 loss: tensor(0.0001, grad_fn=

epoch: 741 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 742 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 743 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 744 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 745 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 746 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 747 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 748 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 749 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 750 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 751 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 752 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 753 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 754 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 755 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 756 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 757 loss: tensor(0.0001, grad_fn=

epoch: 889 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 890 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 891 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 892 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 893 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 894 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 895 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 896 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 897 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 898 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 899 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 900 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 901 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 902 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 903 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 904 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 905 loss: tensor(0.0001, grad_fn=

epoch: 1037 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1038 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1039 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1040 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1041 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1042 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1043 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1044 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1045 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1046 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1047 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1048 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1049 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1050 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1051 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1052 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1053 loss: tensor

epoch: 1183 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1184 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1185 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1186 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1187 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1188 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1189 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1190 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1191 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1192 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1193 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1194 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1195 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1196 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1197 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1198 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1199 loss: tensor

epoch: 1333 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1334 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1335 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1336 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1337 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1338 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1339 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1340 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1341 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1342 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1343 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1344 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1345 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1346 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1347 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1348 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1349 loss: tensor

epoch: 1482 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1483 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1484 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1485 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1486 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1487 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1488 loss: tensor(0.0002, grad_fn=<MseLossBackward0>)
epoch: 1489 loss: tensor(0.0002, grad_fn=<MseLossBackward0>)
epoch: 1490 loss: tensor(0.0002, grad_fn=<MseLossBackward0>)
epoch: 1491 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1492 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1493 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1494 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1495 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1496 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1497 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1498 loss: tensor

epoch: 1629 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1630 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1631 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1632 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1633 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1634 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1635 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1636 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1637 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1638 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1639 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1640 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1641 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1642 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1643 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1644 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1645 loss: tensor

epoch: 1777 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1778 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1779 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1780 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1781 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1782 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1783 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1784 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1785 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1786 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1787 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1788 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1789 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1790 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1791 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1792 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1793 loss: tensor

epoch: 1924 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1925 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1926 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1927 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1928 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1929 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1930 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1931 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1932 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1933 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1934 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1935 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1936 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1937 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1938 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1939 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 1940 loss: tensor

epoch: 2073 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2074 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2075 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2076 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2077 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2078 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2079 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2080 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2081 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2082 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2083 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2084 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2085 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2086 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2087 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2088 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2089 loss: tensor

epoch: 2219 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2220 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2221 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2222 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2223 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2224 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2225 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2226 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2227 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2228 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2229 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2230 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2231 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2232 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2233 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2234 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2235 loss: tensor

epoch: 2367 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2368 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2369 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2370 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2371 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2372 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2373 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2374 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2375 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2376 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2377 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2378 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2379 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2380 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2381 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2382 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2383 loss: tensor

epoch: 2514 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2515 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2516 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2517 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2518 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2519 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2520 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2521 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2522 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2523 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2524 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2525 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2526 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2527 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2528 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2529 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2530 loss: tensor

epoch: 2663 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2664 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2665 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2666 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2667 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2668 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2669 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2670 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2671 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2672 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2673 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2674 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2675 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2676 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2677 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2678 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2679 loss: tensor

epoch: 2810 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2811 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2812 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2813 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2814 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2815 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2816 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2817 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2818 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2819 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2820 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2821 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2822 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2823 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2824 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2825 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2826 loss: tensor

epoch: 2958 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2959 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2960 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2961 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2962 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2963 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2964 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2965 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2966 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2967 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2968 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2969 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2970 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2971 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2972 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2973 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 2974 loss: tensor

epoch: 3105 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3106 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3107 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3108 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3109 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3110 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3111 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3112 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3113 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3114 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3115 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3116 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3117 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3118 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3119 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3120 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3121 loss: tensor

epoch: 3251 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3252 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3253 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3254 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3255 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3256 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3257 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3258 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3259 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3260 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3261 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3262 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3263 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3264 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3265 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3266 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3267 loss: tensor

epoch: 3398 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3399 loss: tensor(9.9984e-05, grad_fn=<MseLossBackward0>)
epoch: 3400 loss: tensor(9.9973e-05, grad_fn=<MseLossBackward0>)
epoch: 3401 loss: tensor(9.9968e-05, grad_fn=<MseLossBackward0>)
epoch: 3402 loss: tensor(9.9964e-05, grad_fn=<MseLossBackward0>)
epoch: 3403 loss: tensor(9.9964e-05, grad_fn=<MseLossBackward0>)
epoch: 3404 loss: tensor(9.9966e-05, grad_fn=<MseLossBackward0>)
epoch: 3405 loss: tensor(9.9969e-05, grad_fn=<MseLossBackward0>)
epoch: 3406 loss: tensor(9.9973e-05, grad_fn=<MseLossBackward0>)
epoch: 3407 loss: tensor(9.9979e-05, grad_fn=<MseLossBackward0>)
epoch: 3408 loss: tensor(9.9984e-05, grad_fn=<MseLossBackward0>)
epoch: 3409 loss: tensor(9.9991e-05, grad_fn=<MseLossBackward0>)
epoch: 3410 loss: tensor(9.9998e-05, grad_fn=<MseLossBackward0>)
epoch: 3411 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3412 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3413 loss: tensor(0.0001, grad

epoch: 3548 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3549 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3550 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3551 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3552 loss: tensor(9.9510e-05, grad_fn=<MseLossBackward0>)
epoch: 3553 loss: tensor(9.9676e-05, grad_fn=<MseLossBackward0>)
epoch: 3554 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3555 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3556 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3557 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3558 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3559 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3560 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3561 loss: tensor(9.9922e-05, grad_fn=<MseLossBackward0>)
epoch: 3562 loss: tensor(9.9533e-05, grad_fn=<MseLossBackward0>)
epoch: 3563 loss: tensor(9.9460e-05, grad_fn=<MseLossBackward0>)
epoc

epoch: 3695 loss: tensor(9.9046e-05, grad_fn=<MseLossBackward0>)
epoch: 3696 loss: tensor(9.9036e-05, grad_fn=<MseLossBackward0>)
epoch: 3697 loss: tensor(9.9035e-05, grad_fn=<MseLossBackward0>)
epoch: 3698 loss: tensor(9.9044e-05, grad_fn=<MseLossBackward0>)
epoch: 3699 loss: tensor(9.9055e-05, grad_fn=<MseLossBackward0>)
epoch: 3700 loss: tensor(9.9065e-05, grad_fn=<MseLossBackward0>)
epoch: 3701 loss: tensor(9.9071e-05, grad_fn=<MseLossBackward0>)
epoch: 3702 loss: tensor(9.9074e-05, grad_fn=<MseLossBackward0>)
epoch: 3703 loss: tensor(9.9079e-05, grad_fn=<MseLossBackward0>)
epoch: 3704 loss: tensor(9.9086e-05, grad_fn=<MseLossBackward0>)
epoch: 3705 loss: tensor(9.9101e-05, grad_fn=<MseLossBackward0>)
epoch: 3706 loss: tensor(9.9126e-05, grad_fn=<MseLossBackward0>)
epoch: 3707 loss: tensor(9.9161e-05, grad_fn=<MseLossBackward0>)
epoch: 3708 loss: tensor(9.9212e-05, grad_fn=<MseLossBackward0>)
epoch: 3709 loss: tensor(9.9277e-05, grad_fn=<MseLossBackward0>)
epoch: 3710 loss: tensor(

epoch: 3845 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3846 loss: tensor(9.9521e-05, grad_fn=<MseLossBackward0>)
epoch: 3847 loss: tensor(9.8977e-05, grad_fn=<MseLossBackward0>)
epoch: 3848 loss: tensor(9.8768e-05, grad_fn=<MseLossBackward0>)
epoch: 3849 loss: tensor(9.8850e-05, grad_fn=<MseLossBackward0>)
epoch: 3850 loss: tensor(9.9030e-05, grad_fn=<MseLossBackward0>)
epoch: 3851 loss: tensor(9.9120e-05, grad_fn=<MseLossBackward0>)
epoch: 3852 loss: tensor(9.9046e-05, grad_fn=<MseLossBackward0>)
epoch: 3853 loss: tensor(9.8870e-05, grad_fn=<MseLossBackward0>)
epoch: 3854 loss: tensor(9.8716e-05, grad_fn=<MseLossBackward0>)
epoch: 3855 loss: tensor(9.8680e-05, grad_fn=<MseLossBackward0>)
epoch: 3856 loss: tensor(9.8770e-05, grad_fn=<MseLossBackward0>)
epoch: 3857 loss: tensor(9.8916e-05, grad_fn=<MseLossBackward0>)
epoch: 3858 loss: tensor(9.9021e-05, grad_fn=<MseLossBackward0>)
epoch: 3859 loss: tensor(9.9029e-05, grad_fn=<MseLossBackward0>)
epoch: 3860 loss: tensor(9.89

epoch: 3994 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3995 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3996 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3997 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3998 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 3999 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 4000 loss: tensor(9.8805e-05, grad_fn=<MseLossBackward0>)
epoch: 4001 loss: tensor(9.8141e-05, grad_fn=<MseLossBackward0>)
epoch: 4002 loss: tensor(9.8267e-05, grad_fn=<MseLossBackward0>)
epoch: 4003 loss: tensor(9.8953e-05, grad_fn=<MseLossBackward0>)
epoch: 4004 loss: tensor(9.9802e-05, grad_fn=<MseLossBackward0>)
epoch: 4005 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 4006 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 4007 loss: tensor(0.0001, grad_fn=<MseLossBackward0>)
epoch: 4008 loss: tensor(9.9762e-05, grad_fn=<MseLossBackward0>)
epoch: 4009 loss: tensor(9.9104e-05, grad_fn=<MseLossBackward

epoch: 4142 loss: tensor(9.8365e-05, grad_fn=<MseLossBackward0>)
epoch: 4143 loss: tensor(9.8302e-05, grad_fn=<MseLossBackward0>)
epoch: 4144 loss: tensor(9.8215e-05, grad_fn=<MseLossBackward0>)
epoch: 4145 loss: tensor(9.8115e-05, grad_fn=<MseLossBackward0>)
epoch: 4146 loss: tensor(9.8016e-05, grad_fn=<MseLossBackward0>)
epoch: 4147 loss: tensor(9.7921e-05, grad_fn=<MseLossBackward0>)
epoch: 4148 loss: tensor(9.7836e-05, grad_fn=<MseLossBackward0>)
epoch: 4149 loss: tensor(9.7766e-05, grad_fn=<MseLossBackward0>)
epoch: 4150 loss: tensor(9.7713e-05, grad_fn=<MseLossBackward0>)
epoch: 4151 loss: tensor(9.7674e-05, grad_fn=<MseLossBackward0>)
epoch: 4152 loss: tensor(9.7647e-05, grad_fn=<MseLossBackward0>)
epoch: 4153 loss: tensor(9.7630e-05, grad_fn=<MseLossBackward0>)
epoch: 4154 loss: tensor(9.7622e-05, grad_fn=<MseLossBackward0>)
epoch: 4155 loss: tensor(9.7619e-05, grad_fn=<MseLossBackward0>)
epoch: 4156 loss: tensor(9.7621e-05, grad_fn=<MseLossBackward0>)
epoch: 4157 loss: tensor(

epoch: 4292 loss: tensor(9.7892e-05, grad_fn=<MseLossBackward0>)
epoch: 4293 loss: tensor(9.7726e-05, grad_fn=<MseLossBackward0>)
epoch: 4294 loss: tensor(9.7546e-05, grad_fn=<MseLossBackward0>)
epoch: 4295 loss: tensor(9.7469e-05, grad_fn=<MseLossBackward0>)
epoch: 4296 loss: tensor(9.7506e-05, grad_fn=<MseLossBackward0>)
epoch: 4297 loss: tensor(9.7573e-05, grad_fn=<MseLossBackward0>)
epoch: 4298 loss: tensor(9.7574e-05, grad_fn=<MseLossBackward0>)
epoch: 4299 loss: tensor(9.7469e-05, grad_fn=<MseLossBackward0>)
epoch: 4300 loss: tensor(9.7305e-05, grad_fn=<MseLossBackward0>)
epoch: 4301 loss: tensor(9.7175e-05, grad_fn=<MseLossBackward0>)
epoch: 4302 loss: tensor(9.7140e-05, grad_fn=<MseLossBackward0>)
epoch: 4303 loss: tensor(9.7201e-05, grad_fn=<MseLossBackward0>)
epoch: 4304 loss: tensor(9.7303e-05, grad_fn=<MseLossBackward0>)
epoch: 4305 loss: tensor(9.7376e-05, grad_fn=<MseLossBackward0>)
epoch: 4306 loss: tensor(9.7375e-05, grad_fn=<MseLossBackward0>)
epoch: 4307 loss: tensor(

epoch: 4437 loss: tensor(9.6732e-05, grad_fn=<MseLossBackward0>)
epoch: 4438 loss: tensor(9.6703e-05, grad_fn=<MseLossBackward0>)
epoch: 4439 loss: tensor(9.6676e-05, grad_fn=<MseLossBackward0>)
epoch: 4440 loss: tensor(9.6657e-05, grad_fn=<MseLossBackward0>)
epoch: 4441 loss: tensor(9.6653e-05, grad_fn=<MseLossBackward0>)
epoch: 4442 loss: tensor(9.6661e-05, grad_fn=<MseLossBackward0>)
epoch: 4443 loss: tensor(9.6673e-05, grad_fn=<MseLossBackward0>)
epoch: 4444 loss: tensor(9.6684e-05, grad_fn=<MseLossBackward0>)
epoch: 4445 loss: tensor(9.6688e-05, grad_fn=<MseLossBackward0>)
epoch: 4446 loss: tensor(9.6685e-05, grad_fn=<MseLossBackward0>)
epoch: 4447 loss: tensor(9.6678e-05, grad_fn=<MseLossBackward0>)
epoch: 4448 loss: tensor(9.6672e-05, grad_fn=<MseLossBackward0>)
epoch: 4449 loss: tensor(9.6669e-05, grad_fn=<MseLossBackward0>)
epoch: 4450 loss: tensor(9.6673e-05, grad_fn=<MseLossBackward0>)
epoch: 4451 loss: tensor(9.6686e-05, grad_fn=<MseLossBackward0>)
epoch: 4452 loss: tensor(

epoch: 4586 loss: tensor(9.6727e-05, grad_fn=<MseLossBackward0>)
epoch: 4587 loss: tensor(9.6653e-05, grad_fn=<MseLossBackward0>)
epoch: 4588 loss: tensor(9.6479e-05, grad_fn=<MseLossBackward0>)
epoch: 4589 loss: tensor(9.6295e-05, grad_fn=<MseLossBackward0>)
epoch: 4590 loss: tensor(9.6186e-05, grad_fn=<MseLossBackward0>)
epoch: 4591 loss: tensor(9.6180e-05, grad_fn=<MseLossBackward0>)
epoch: 4592 loss: tensor(9.6248e-05, grad_fn=<MseLossBackward0>)
epoch: 4593 loss: tensor(9.6334e-05, grad_fn=<MseLossBackward0>)
epoch: 4594 loss: tensor(9.6379e-05, grad_fn=<MseLossBackward0>)
epoch: 4595 loss: tensor(9.6363e-05, grad_fn=<MseLossBackward0>)
epoch: 4596 loss: tensor(9.6295e-05, grad_fn=<MseLossBackward0>)
epoch: 4597 loss: tensor(9.6214e-05, grad_fn=<MseLossBackward0>)
epoch: 4598 loss: tensor(9.6155e-05, grad_fn=<MseLossBackward0>)
epoch: 4599 loss: tensor(9.6138e-05, grad_fn=<MseLossBackward0>)
epoch: 4600 loss: tensor(9.6158e-05, grad_fn=<MseLossBackward0>)
epoch: 4601 loss: tensor(

epoch: 4734 loss: tensor(9.6555e-05, grad_fn=<MseLossBackward0>)
epoch: 4735 loss: tensor(9.5859e-05, grad_fn=<MseLossBackward0>)
epoch: 4736 loss: tensor(9.6484e-05, grad_fn=<MseLossBackward0>)
epoch: 4737 loss: tensor(9.7698e-05, grad_fn=<MseLossBackward0>)
epoch: 4738 loss: tensor(9.8553e-05, grad_fn=<MseLossBackward0>)
epoch: 4739 loss: tensor(9.8488e-05, grad_fn=<MseLossBackward0>)
epoch: 4740 loss: tensor(9.7616e-05, grad_fn=<MseLossBackward0>)
epoch: 4741 loss: tensor(9.6541e-05, grad_fn=<MseLossBackward0>)
epoch: 4742 loss: tensor(9.5881e-05, grad_fn=<MseLossBackward0>)
epoch: 4743 loss: tensor(9.5887e-05, grad_fn=<MseLossBackward0>)
epoch: 4744 loss: tensor(9.6351e-05, grad_fn=<MseLossBackward0>)
epoch: 4745 loss: tensor(9.6826e-05, grad_fn=<MseLossBackward0>)
epoch: 4746 loss: tensor(9.6955e-05, grad_fn=<MseLossBackward0>)
epoch: 4747 loss: tensor(9.6671e-05, grad_fn=<MseLossBackward0>)
epoch: 4748 loss: tensor(9.6180e-05, grad_fn=<MseLossBackward0>)
epoch: 4749 loss: tensor(

epoch: 4880 loss: tensor(9.5294e-05, grad_fn=<MseLossBackward0>)
epoch: 4881 loss: tensor(9.5298e-05, grad_fn=<MseLossBackward0>)
epoch: 4882 loss: tensor(9.5304e-05, grad_fn=<MseLossBackward0>)
epoch: 4883 loss: tensor(9.5314e-05, grad_fn=<MseLossBackward0>)
epoch: 4884 loss: tensor(9.5331e-05, grad_fn=<MseLossBackward0>)
epoch: 4885 loss: tensor(9.5360e-05, grad_fn=<MseLossBackward0>)
epoch: 4886 loss: tensor(9.5403e-05, grad_fn=<MseLossBackward0>)
epoch: 4887 loss: tensor(9.5468e-05, grad_fn=<MseLossBackward0>)
epoch: 4888 loss: tensor(9.5567e-05, grad_fn=<MseLossBackward0>)
epoch: 4889 loss: tensor(9.5716e-05, grad_fn=<MseLossBackward0>)
epoch: 4890 loss: tensor(9.5939e-05, grad_fn=<MseLossBackward0>)
epoch: 4891 loss: tensor(9.6274e-05, grad_fn=<MseLossBackward0>)
epoch: 4892 loss: tensor(9.6774e-05, grad_fn=<MseLossBackward0>)
epoch: 4893 loss: tensor(9.7519e-05, grad_fn=<MseLossBackward0>)
epoch: 4894 loss: tensor(9.8611e-05, grad_fn=<MseLossBackward0>)
epoch: 4895 loss: tensor(

epoch: 5027 loss: tensor(9.4825e-05, grad_fn=<MseLossBackward0>)
epoch: 5028 loss: tensor(9.4803e-05, grad_fn=<MseLossBackward0>)
epoch: 5029 loss: tensor(9.4801e-05, grad_fn=<MseLossBackward0>)
epoch: 5030 loss: tensor(9.4815e-05, grad_fn=<MseLossBackward0>)
epoch: 5031 loss: tensor(9.4830e-05, grad_fn=<MseLossBackward0>)
epoch: 5032 loss: tensor(9.4837e-05, grad_fn=<MseLossBackward0>)
epoch: 5033 loss: tensor(9.4833e-05, grad_fn=<MseLossBackward0>)
epoch: 5034 loss: tensor(9.4819e-05, grad_fn=<MseLossBackward0>)
epoch: 5035 loss: tensor(9.4800e-05, grad_fn=<MseLossBackward0>)
epoch: 5036 loss: tensor(9.4786e-05, grad_fn=<MseLossBackward0>)
epoch: 5037 loss: tensor(9.4776e-05, grad_fn=<MseLossBackward0>)
epoch: 5038 loss: tensor(9.4773e-05, grad_fn=<MseLossBackward0>)
epoch: 5039 loss: tensor(9.4776e-05, grad_fn=<MseLossBackward0>)
epoch: 5040 loss: tensor(9.4779e-05, grad_fn=<MseLossBackward0>)
epoch: 5041 loss: tensor(9.4780e-05, grad_fn=<MseLossBackward0>)
epoch: 5042 loss: tensor(

epoch: 5175 loss: tensor(9.4596e-05, grad_fn=<MseLossBackward0>)
epoch: 5176 loss: tensor(9.4585e-05, grad_fn=<MseLossBackward0>)
epoch: 5177 loss: tensor(9.4988e-05, grad_fn=<MseLossBackward0>)
epoch: 5178 loss: tensor(9.5475e-05, grad_fn=<MseLossBackward0>)
epoch: 5179 loss: tensor(9.5756e-05, grad_fn=<MseLossBackward0>)
epoch: 5180 loss: tensor(9.5700e-05, grad_fn=<MseLossBackward0>)
epoch: 5181 loss: tensor(9.5368e-05, grad_fn=<MseLossBackward0>)
epoch: 5182 loss: tensor(9.4939e-05, grad_fn=<MseLossBackward0>)
epoch: 5183 loss: tensor(9.4605e-05, grad_fn=<MseLossBackward0>)
epoch: 5184 loss: tensor(9.4476e-05, grad_fn=<MseLossBackward0>)
epoch: 5185 loss: tensor(9.4540e-05, grad_fn=<MseLossBackward0>)
epoch: 5186 loss: tensor(9.4700e-05, grad_fn=<MseLossBackward0>)
epoch: 5187 loss: tensor(9.4837e-05, grad_fn=<MseLossBackward0>)
epoch: 5188 loss: tensor(9.4870e-05, grad_fn=<MseLossBackward0>)
epoch: 5189 loss: tensor(9.4787e-05, grad_fn=<MseLossBackward0>)
epoch: 5190 loss: tensor(

epoch: 5320 loss: tensor(9.4307e-05, grad_fn=<MseLossBackward0>)
epoch: 5321 loss: tensor(9.4228e-05, grad_fn=<MseLossBackward0>)
epoch: 5322 loss: tensor(9.4116e-05, grad_fn=<MseLossBackward0>)
epoch: 5323 loss: tensor(9.4074e-05, grad_fn=<MseLossBackward0>)
epoch: 5324 loss: tensor(9.4118e-05, grad_fn=<MseLossBackward0>)
epoch: 5325 loss: tensor(9.4178e-05, grad_fn=<MseLossBackward0>)
epoch: 5326 loss: tensor(9.4175e-05, grad_fn=<MseLossBackward0>)
epoch: 5327 loss: tensor(9.4090e-05, grad_fn=<MseLossBackward0>)
epoch: 5328 loss: tensor(9.3969e-05, grad_fn=<MseLossBackward0>)
epoch: 5329 loss: tensor(9.3892e-05, grad_fn=<MseLossBackward0>)
epoch: 5330 loss: tensor(9.3893e-05, grad_fn=<MseLossBackward0>)
epoch: 5331 loss: tensor(9.3952e-05, grad_fn=<MseLossBackward0>)
epoch: 5332 loss: tensor(9.4013e-05, grad_fn=<MseLossBackward0>)
epoch: 5333 loss: tensor(9.4032e-05, grad_fn=<MseLossBackward0>)
epoch: 5334 loss: tensor(9.4002e-05, grad_fn=<MseLossBackward0>)
epoch: 5335 loss: tensor(

epoch: 5468 loss: tensor(9.3513e-05, grad_fn=<MseLossBackward0>)
epoch: 5469 loss: tensor(9.3531e-05, grad_fn=<MseLossBackward0>)
epoch: 5470 loss: tensor(9.3534e-05, grad_fn=<MseLossBackward0>)
epoch: 5471 loss: tensor(9.3520e-05, grad_fn=<MseLossBackward0>)
epoch: 5472 loss: tensor(9.3497e-05, grad_fn=<MseLossBackward0>)
epoch: 5473 loss: tensor(9.3475e-05, grad_fn=<MseLossBackward0>)
epoch: 5474 loss: tensor(9.3464e-05, grad_fn=<MseLossBackward0>)
epoch: 5475 loss: tensor(9.3464e-05, grad_fn=<MseLossBackward0>)
epoch: 5476 loss: tensor(9.3472e-05, grad_fn=<MseLossBackward0>)
epoch: 5477 loss: tensor(9.3482e-05, grad_fn=<MseLossBackward0>)
epoch: 5478 loss: tensor(9.3486e-05, grad_fn=<MseLossBackward0>)
epoch: 5479 loss: tensor(9.3487e-05, grad_fn=<MseLossBackward0>)
epoch: 5480 loss: tensor(9.3482e-05, grad_fn=<MseLossBackward0>)
epoch: 5481 loss: tensor(9.3478e-05, grad_fn=<MseLossBackward0>)
epoch: 5482 loss: tensor(9.3480e-05, grad_fn=<MseLossBackward0>)
epoch: 5483 loss: tensor(

epoch: 5617 loss: tensor(9.3961e-05, grad_fn=<MseLossBackward0>)
epoch: 5618 loss: tensor(9.3438e-05, grad_fn=<MseLossBackward0>)
epoch: 5619 loss: tensor(9.3171e-05, grad_fn=<MseLossBackward0>)
epoch: 5620 loss: tensor(9.3198e-05, grad_fn=<MseLossBackward0>)
epoch: 5621 loss: tensor(9.3409e-05, grad_fn=<MseLossBackward0>)
epoch: 5622 loss: tensor(9.3635e-05, grad_fn=<MseLossBackward0>)
epoch: 5623 loss: tensor(9.3737e-05, grad_fn=<MseLossBackward0>)
epoch: 5624 loss: tensor(9.3668e-05, grad_fn=<MseLossBackward0>)
epoch: 5625 loss: tensor(9.3469e-05, grad_fn=<MseLossBackward0>)
epoch: 5626 loss: tensor(9.3237e-05, grad_fn=<MseLossBackward0>)
epoch: 5627 loss: tensor(9.3071e-05, grad_fn=<MseLossBackward0>)
epoch: 5628 loss: tensor(9.3020e-05, grad_fn=<MseLossBackward0>)
epoch: 5629 loss: tensor(9.3076e-05, grad_fn=<MseLossBackward0>)
epoch: 5630 loss: tensor(9.3189e-05, grad_fn=<MseLossBackward0>)
epoch: 5631 loss: tensor(9.3287e-05, grad_fn=<MseLossBackward0>)
epoch: 5632 loss: tensor(

epoch: 5763 loss: tensor(9.3128e-05, grad_fn=<MseLossBackward0>)
epoch: 5764 loss: tensor(9.3210e-05, grad_fn=<MseLossBackward0>)
epoch: 5765 loss: tensor(9.3295e-05, grad_fn=<MseLossBackward0>)
epoch: 5766 loss: tensor(9.3343e-05, grad_fn=<MseLossBackward0>)
epoch: 5767 loss: tensor(9.3332e-05, grad_fn=<MseLossBackward0>)
epoch: 5768 loss: tensor(9.3262e-05, grad_fn=<MseLossBackward0>)
epoch: 5769 loss: tensor(9.3149e-05, grad_fn=<MseLossBackward0>)
epoch: 5770 loss: tensor(9.3020e-05, grad_fn=<MseLossBackward0>)
epoch: 5771 loss: tensor(9.2896e-05, grad_fn=<MseLossBackward0>)
epoch: 5772 loss: tensor(9.2797e-05, grad_fn=<MseLossBackward0>)
epoch: 5773 loss: tensor(9.2738e-05, grad_fn=<MseLossBackward0>)
epoch: 5774 loss: tensor(9.2711e-05, grad_fn=<MseLossBackward0>)
epoch: 5775 loss: tensor(9.2712e-05, grad_fn=<MseLossBackward0>)
epoch: 5776 loss: tensor(9.2725e-05, grad_fn=<MseLossBackward0>)
epoch: 5777 loss: tensor(9.2739e-05, grad_fn=<MseLossBackward0>)
epoch: 5778 loss: tensor(

epoch: 5909 loss: tensor(9.2222e-05, grad_fn=<MseLossBackward0>)
epoch: 5910 loss: tensor(9.2209e-05, grad_fn=<MseLossBackward0>)
epoch: 5911 loss: tensor(9.2233e-05, grad_fn=<MseLossBackward0>)
epoch: 5912 loss: tensor(9.2272e-05, grad_fn=<MseLossBackward0>)
epoch: 5913 loss: tensor(9.2303e-05, grad_fn=<MseLossBackward0>)
epoch: 5914 loss: tensor(9.2310e-05, grad_fn=<MseLossBackward0>)
epoch: 5915 loss: tensor(9.2293e-05, grad_fn=<MseLossBackward0>)
epoch: 5916 loss: tensor(9.2259e-05, grad_fn=<MseLossBackward0>)
epoch: 5917 loss: tensor(9.2222e-05, grad_fn=<MseLossBackward0>)
epoch: 5918 loss: tensor(9.2190e-05, grad_fn=<MseLossBackward0>)
epoch: 5919 loss: tensor(9.2175e-05, grad_fn=<MseLossBackward0>)
epoch: 5920 loss: tensor(9.2175e-05, grad_fn=<MseLossBackward0>)
epoch: 5921 loss: tensor(9.2185e-05, grad_fn=<MseLossBackward0>)
epoch: 5922 loss: tensor(9.2197e-05, grad_fn=<MseLossBackward0>)
epoch: 5923 loss: tensor(9.2205e-05, grad_fn=<MseLossBackward0>)
epoch: 5924 loss: tensor(

epoch: 6057 loss: tensor(9.1799e-05, grad_fn=<MseLossBackward0>)
epoch: 6058 loss: tensor(9.1867e-05, grad_fn=<MseLossBackward0>)
epoch: 6059 loss: tensor(9.1973e-05, grad_fn=<MseLossBackward0>)
epoch: 6060 loss: tensor(9.2053e-05, grad_fn=<MseLossBackward0>)
epoch: 6061 loss: tensor(9.2073e-05, grad_fn=<MseLossBackward0>)
epoch: 6062 loss: tensor(9.2027e-05, grad_fn=<MseLossBackward0>)
epoch: 6063 loss: tensor(9.1938e-05, grad_fn=<MseLossBackward0>)
epoch: 6064 loss: tensor(9.1846e-05, grad_fn=<MseLossBackward0>)
epoch: 6065 loss: tensor(9.1780e-05, grad_fn=<MseLossBackward0>)
epoch: 6066 loss: tensor(9.1757e-05, grad_fn=<MseLossBackward0>)
epoch: 6067 loss: tensor(9.1771e-05, grad_fn=<MseLossBackward0>)
epoch: 6068 loss: tensor(9.1804e-05, grad_fn=<MseLossBackward0>)
epoch: 6069 loss: tensor(9.1837e-05, grad_fn=<MseLossBackward0>)
epoch: 6070 loss: tensor(9.1854e-05, grad_fn=<MseLossBackward0>)
epoch: 6071 loss: tensor(9.1847e-05, grad_fn=<MseLossBackward0>)
epoch: 6072 loss: tensor(

epoch: 6204 loss: tensor(9.5720e-05, grad_fn=<MseLossBackward0>)
epoch: 6205 loss: tensor(9.5822e-05, grad_fn=<MseLossBackward0>)
epoch: 6206 loss: tensor(9.5705e-05, grad_fn=<MseLossBackward0>)
epoch: 6207 loss: tensor(9.5342e-05, grad_fn=<MseLossBackward0>)
epoch: 6208 loss: tensor(9.4749e-05, grad_fn=<MseLossBackward0>)
epoch: 6209 loss: tensor(9.3999e-05, grad_fn=<MseLossBackward0>)
epoch: 6210 loss: tensor(9.3194e-05, grad_fn=<MseLossBackward0>)
epoch: 6211 loss: tensor(9.2450e-05, grad_fn=<MseLossBackward0>)
epoch: 6212 loss: tensor(9.1868e-05, grad_fn=<MseLossBackward0>)
epoch: 6213 loss: tensor(9.1502e-05, grad_fn=<MseLossBackward0>)
epoch: 6214 loss: tensor(9.1357e-05, grad_fn=<MseLossBackward0>)
epoch: 6215 loss: tensor(9.1401e-05, grad_fn=<MseLossBackward0>)
epoch: 6216 loss: tensor(9.1572e-05, grad_fn=<MseLossBackward0>)
epoch: 6217 loss: tensor(9.1798e-05, grad_fn=<MseLossBackward0>)
epoch: 6218 loss: tensor(9.2024e-05, grad_fn=<MseLossBackward0>)
epoch: 6219 loss: tensor(

epoch: 6352 loss: tensor(9.0954e-05, grad_fn=<MseLossBackward0>)
epoch: 6353 loss: tensor(9.0959e-05, grad_fn=<MseLossBackward0>)
epoch: 6354 loss: tensor(9.0966e-05, grad_fn=<MseLossBackward0>)
epoch: 6355 loss: tensor(9.0969e-05, grad_fn=<MseLossBackward0>)
epoch: 6356 loss: tensor(9.0968e-05, grad_fn=<MseLossBackward0>)
epoch: 6357 loss: tensor(9.0963e-05, grad_fn=<MseLossBackward0>)
epoch: 6358 loss: tensor(9.0955e-05, grad_fn=<MseLossBackward0>)
epoch: 6359 loss: tensor(9.0948e-05, grad_fn=<MseLossBackward0>)
epoch: 6360 loss: tensor(9.0943e-05, grad_fn=<MseLossBackward0>)
epoch: 6361 loss: tensor(9.0941e-05, grad_fn=<MseLossBackward0>)
epoch: 6362 loss: tensor(9.0939e-05, grad_fn=<MseLossBackward0>)
epoch: 6363 loss: tensor(9.0938e-05, grad_fn=<MseLossBackward0>)
epoch: 6364 loss: tensor(9.0938e-05, grad_fn=<MseLossBackward0>)
epoch: 6365 loss: tensor(9.0935e-05, grad_fn=<MseLossBackward0>)
epoch: 6366 loss: tensor(9.0933e-05, grad_fn=<MseLossBackward0>)
epoch: 6367 loss: tensor(

epoch: 6500 loss: tensor(9.0571e-05, grad_fn=<MseLossBackward0>)
epoch: 6501 loss: tensor(9.0559e-05, grad_fn=<MseLossBackward0>)
epoch: 6502 loss: tensor(9.0549e-05, grad_fn=<MseLossBackward0>)
epoch: 6503 loss: tensor(9.0540e-05, grad_fn=<MseLossBackward0>)
epoch: 6504 loss: tensor(9.0532e-05, grad_fn=<MseLossBackward0>)
epoch: 6505 loss: tensor(9.0525e-05, grad_fn=<MseLossBackward0>)
epoch: 6506 loss: tensor(9.0520e-05, grad_fn=<MseLossBackward0>)
epoch: 6507 loss: tensor(9.0515e-05, grad_fn=<MseLossBackward0>)
epoch: 6508 loss: tensor(9.0512e-05, grad_fn=<MseLossBackward0>)
epoch: 6509 loss: tensor(9.0508e-05, grad_fn=<MseLossBackward0>)
epoch: 6510 loss: tensor(9.0504e-05, grad_fn=<MseLossBackward0>)
epoch: 6511 loss: tensor(9.0501e-05, grad_fn=<MseLossBackward0>)
epoch: 6512 loss: tensor(9.0498e-05, grad_fn=<MseLossBackward0>)
epoch: 6513 loss: tensor(9.0495e-05, grad_fn=<MseLossBackward0>)
epoch: 6514 loss: tensor(9.0494e-05, grad_fn=<MseLossBackward0>)
epoch: 6515 loss: tensor(

epoch: 6648 loss: tensor(9.0110e-05, grad_fn=<MseLossBackward0>)
epoch: 6649 loss: tensor(9.0107e-05, grad_fn=<MseLossBackward0>)
epoch: 6650 loss: tensor(9.0105e-05, grad_fn=<MseLossBackward0>)
epoch: 6651 loss: tensor(9.0102e-05, grad_fn=<MseLossBackward0>)
epoch: 6652 loss: tensor(9.0099e-05, grad_fn=<MseLossBackward0>)
epoch: 6653 loss: tensor(9.0096e-05, grad_fn=<MseLossBackward0>)
epoch: 6654 loss: tensor(9.0094e-05, grad_fn=<MseLossBackward0>)
epoch: 6655 loss: tensor(9.0091e-05, grad_fn=<MseLossBackward0>)
epoch: 6656 loss: tensor(9.0089e-05, grad_fn=<MseLossBackward0>)
epoch: 6657 loss: tensor(9.0087e-05, grad_fn=<MseLossBackward0>)
epoch: 6658 loss: tensor(9.0085e-05, grad_fn=<MseLossBackward0>)
epoch: 6659 loss: tensor(9.0083e-05, grad_fn=<MseLossBackward0>)
epoch: 6660 loss: tensor(9.0081e-05, grad_fn=<MseLossBackward0>)
epoch: 6661 loss: tensor(9.0079e-05, grad_fn=<MseLossBackward0>)
epoch: 6662 loss: tensor(9.0079e-05, grad_fn=<MseLossBackward0>)
epoch: 6663 loss: tensor(

epoch: 6798 loss: tensor(9.0157e-05, grad_fn=<MseLossBackward0>)
epoch: 6799 loss: tensor(9.0265e-05, grad_fn=<MseLossBackward0>)
epoch: 6800 loss: tensor(9.0407e-05, grad_fn=<MseLossBackward0>)
epoch: 6801 loss: tensor(9.0594e-05, grad_fn=<MseLossBackward0>)
epoch: 6802 loss: tensor(9.0838e-05, grad_fn=<MseLossBackward0>)
epoch: 6803 loss: tensor(9.1149e-05, grad_fn=<MseLossBackward0>)
epoch: 6804 loss: tensor(9.1544e-05, grad_fn=<MseLossBackward0>)
epoch: 6805 loss: tensor(9.2036e-05, grad_fn=<MseLossBackward0>)
epoch: 6806 loss: tensor(9.2632e-05, grad_fn=<MseLossBackward0>)
epoch: 6807 loss: tensor(9.3332e-05, grad_fn=<MseLossBackward0>)
epoch: 6808 loss: tensor(9.4113e-05, grad_fn=<MseLossBackward0>)
epoch: 6809 loss: tensor(9.4928e-05, grad_fn=<MseLossBackward0>)
epoch: 6810 loss: tensor(9.5690e-05, grad_fn=<MseLossBackward0>)
epoch: 6811 loss: tensor(9.6272e-05, grad_fn=<MseLossBackward0>)
epoch: 6812 loss: tensor(9.6523e-05, grad_fn=<MseLossBackward0>)
epoch: 6813 loss: tensor(

epoch: 6944 loss: tensor(8.9400e-05, grad_fn=<MseLossBackward0>)
epoch: 6945 loss: tensor(8.9438e-05, grad_fn=<MseLossBackward0>)
epoch: 6946 loss: tensor(8.9489e-05, grad_fn=<MseLossBackward0>)
epoch: 6947 loss: tensor(8.9556e-05, grad_fn=<MseLossBackward0>)
epoch: 6948 loss: tensor(8.9648e-05, grad_fn=<MseLossBackward0>)
epoch: 6949 loss: tensor(8.9777e-05, grad_fn=<MseLossBackward0>)
epoch: 6950 loss: tensor(8.9953e-05, grad_fn=<MseLossBackward0>)
epoch: 6951 loss: tensor(9.0193e-05, grad_fn=<MseLossBackward0>)
epoch: 6952 loss: tensor(9.0522e-05, grad_fn=<MseLossBackward0>)
epoch: 6953 loss: tensor(9.0975e-05, grad_fn=<MseLossBackward0>)
epoch: 6954 loss: tensor(9.1597e-05, grad_fn=<MseLossBackward0>)
epoch: 6955 loss: tensor(9.2435e-05, grad_fn=<MseLossBackward0>)
epoch: 6956 loss: tensor(9.3545e-05, grad_fn=<MseLossBackward0>)
epoch: 6957 loss: tensor(9.4978e-05, grad_fn=<MseLossBackward0>)
epoch: 6958 loss: tensor(9.6758e-05, grad_fn=<MseLossBackward0>)
epoch: 6959 loss: tensor(

epoch: 7093 loss: tensor(9.3497e-05, grad_fn=<MseLossBackward0>)
epoch: 7094 loss: tensor(9.4328e-05, grad_fn=<MseLossBackward0>)
epoch: 7095 loss: tensor(9.5351e-05, grad_fn=<MseLossBackward0>)
epoch: 7096 loss: tensor(9.5885e-05, grad_fn=<MseLossBackward0>)
epoch: 7097 loss: tensor(9.5499e-05, grad_fn=<MseLossBackward0>)
epoch: 7098 loss: tensor(9.4212e-05, grad_fn=<MseLossBackward0>)
epoch: 7099 loss: tensor(9.2459e-05, grad_fn=<MseLossBackward0>)
epoch: 7100 loss: tensor(9.0842e-05, grad_fn=<MseLossBackward0>)
epoch: 7101 loss: tensor(8.9795e-05, grad_fn=<MseLossBackward0>)
epoch: 7102 loss: tensor(8.9422e-05, grad_fn=<MseLossBackward0>)
epoch: 7103 loss: tensor(8.9526e-05, grad_fn=<MseLossBackward0>)
epoch: 7104 loss: tensor(8.9798e-05, grad_fn=<MseLossBackward0>)
epoch: 7105 loss: tensor(8.9996e-05, grad_fn=<MseLossBackward0>)
epoch: 7106 loss: tensor(9.0045e-05, grad_fn=<MseLossBackward0>)
epoch: 7107 loss: tensor(9.0003e-05, grad_fn=<MseLossBackward0>)
epoch: 7108 loss: tensor(

epoch: 7241 loss: tensor(9.0253e-05, grad_fn=<MseLossBackward0>)
epoch: 7242 loss: tensor(9.0393e-05, grad_fn=<MseLossBackward0>)
epoch: 7243 loss: tensor(9.0244e-05, grad_fn=<MseLossBackward0>)
epoch: 7244 loss: tensor(8.9867e-05, grad_fn=<MseLossBackward0>)
epoch: 7245 loss: tensor(8.9383e-05, grad_fn=<MseLossBackward0>)
epoch: 7246 loss: tensor(8.8926e-05, grad_fn=<MseLossBackward0>)
epoch: 7247 loss: tensor(8.8597e-05, grad_fn=<MseLossBackward0>)
epoch: 7248 loss: tensor(8.8448e-05, grad_fn=<MseLossBackward0>)
epoch: 7249 loss: tensor(8.8466e-05, grad_fn=<MseLossBackward0>)
epoch: 7250 loss: tensor(8.8597e-05, grad_fn=<MseLossBackward0>)
epoch: 7251 loss: tensor(8.8775e-05, grad_fn=<MseLossBackward0>)
epoch: 7252 loss: tensor(8.8933e-05, grad_fn=<MseLossBackward0>)
epoch: 7253 loss: tensor(8.9021e-05, grad_fn=<MseLossBackward0>)
epoch: 7254 loss: tensor(8.9023e-05, grad_fn=<MseLossBackward0>)
epoch: 7255 loss: tensor(8.8945e-05, grad_fn=<MseLossBackward0>)
epoch: 7256 loss: tensor(

epoch: 7391 loss: tensor(8.8177e-05, grad_fn=<MseLossBackward0>)
epoch: 7392 loss: tensor(8.8163e-05, grad_fn=<MseLossBackward0>)
epoch: 7393 loss: tensor(8.8144e-05, grad_fn=<MseLossBackward0>)
epoch: 7394 loss: tensor(8.8122e-05, grad_fn=<MseLossBackward0>)
epoch: 7395 loss: tensor(8.8099e-05, grad_fn=<MseLossBackward0>)
epoch: 7396 loss: tensor(8.8077e-05, grad_fn=<MseLossBackward0>)
epoch: 7397 loss: tensor(8.8057e-05, grad_fn=<MseLossBackward0>)
epoch: 7398 loss: tensor(8.8041e-05, grad_fn=<MseLossBackward0>)
epoch: 7399 loss: tensor(8.8028e-05, grad_fn=<MseLossBackward0>)
epoch: 7400 loss: tensor(8.8019e-05, grad_fn=<MseLossBackward0>)
epoch: 7401 loss: tensor(8.8013e-05, grad_fn=<MseLossBackward0>)
epoch: 7402 loss: tensor(8.8010e-05, grad_fn=<MseLossBackward0>)
epoch: 7403 loss: tensor(8.8008e-05, grad_fn=<MseLossBackward0>)
epoch: 7404 loss: tensor(8.8007e-05, grad_fn=<MseLossBackward0>)
epoch: 7405 loss: tensor(8.8007e-05, grad_fn=<MseLossBackward0>)
epoch: 7406 loss: tensor(

epoch: 7540 loss: tensor(8.8106e-05, grad_fn=<MseLossBackward0>)
epoch: 7541 loss: tensor(8.7825e-05, grad_fn=<MseLossBackward0>)
epoch: 7542 loss: tensor(8.7847e-05, grad_fn=<MseLossBackward0>)
epoch: 7543 loss: tensor(8.8089e-05, grad_fn=<MseLossBackward0>)
epoch: 7544 loss: tensor(8.8358e-05, grad_fn=<MseLossBackward0>)
epoch: 7545 loss: tensor(8.8482e-05, grad_fn=<MseLossBackward0>)
epoch: 7546 loss: tensor(8.8407e-05, grad_fn=<MseLossBackward0>)
epoch: 7547 loss: tensor(8.8211e-05, grad_fn=<MseLossBackward0>)
epoch: 7548 loss: tensor(8.8027e-05, grad_fn=<MseLossBackward0>)
epoch: 7549 loss: tensor(8.7960e-05, grad_fn=<MseLossBackward0>)
epoch: 7550 loss: tensor(8.8025e-05, grad_fn=<MseLossBackward0>)
epoch: 7551 loss: tensor(8.8166e-05, grad_fn=<MseLossBackward0>)
epoch: 7552 loss: tensor(8.8299e-05, grad_fn=<MseLossBackward0>)
epoch: 7553 loss: tensor(8.8364e-05, grad_fn=<MseLossBackward0>)
epoch: 7554 loss: tensor(8.8355e-05, grad_fn=<MseLossBackward0>)
epoch: 7555 loss: tensor(

epoch: 7687 loss: tensor(9.3077e-05, grad_fn=<MseLossBackward0>)
epoch: 7688 loss: tensor(9.4676e-05, grad_fn=<MseLossBackward0>)
epoch: 7689 loss: tensor(9.6347e-05, grad_fn=<MseLossBackward0>)
epoch: 7690 loss: tensor(9.7776e-05, grad_fn=<MseLossBackward0>)
epoch: 7691 loss: tensor(9.8519e-05, grad_fn=<MseLossBackward0>)
epoch: 7692 loss: tensor(9.8142e-05, grad_fn=<MseLossBackward0>)
epoch: 7693 loss: tensor(9.6458e-05, grad_fn=<MseLossBackward0>)
epoch: 7694 loss: tensor(9.3770e-05, grad_fn=<MseLossBackward0>)
epoch: 7695 loss: tensor(9.0883e-05, grad_fn=<MseLossBackward0>)
epoch: 7696 loss: tensor(8.8712e-05, grad_fn=<MseLossBackward0>)
epoch: 7697 loss: tensor(8.7827e-05, grad_fn=<MseLossBackward0>)
epoch: 7698 loss: tensor(8.8208e-05, grad_fn=<MseLossBackward0>)
epoch: 7699 loss: tensor(8.9351e-05, grad_fn=<MseLossBackward0>)
epoch: 7700 loss: tensor(9.0561e-05, grad_fn=<MseLossBackward0>)
epoch: 7701 loss: tensor(9.1245e-05, grad_fn=<MseLossBackward0>)
epoch: 7702 loss: tensor(

epoch: 7835 loss: tensor(9.4276e-05, grad_fn=<MseLossBackward0>)
epoch: 7836 loss: tensor(9.3815e-05, grad_fn=<MseLossBackward0>)
epoch: 7837 loss: tensor(9.2045e-05, grad_fn=<MseLossBackward0>)
epoch: 7838 loss: tensor(8.9686e-05, grad_fn=<MseLossBackward0>)
epoch: 7839 loss: tensor(8.7737e-05, grad_fn=<MseLossBackward0>)
epoch: 7840 loss: tensor(8.6890e-05, grad_fn=<MseLossBackward0>)
epoch: 7841 loss: tensor(8.7192e-05, grad_fn=<MseLossBackward0>)
epoch: 7842 loss: tensor(8.8143e-05, grad_fn=<MseLossBackward0>)
epoch: 7843 loss: tensor(8.9055e-05, grad_fn=<MseLossBackward0>)
epoch: 7844 loss: tensor(8.9437e-05, grad_fn=<MseLossBackward0>)
epoch: 7845 loss: tensor(8.9189e-05, grad_fn=<MseLossBackward0>)
epoch: 7846 loss: tensor(8.8563e-05, grad_fn=<MseLossBackward0>)
epoch: 7847 loss: tensor(8.7955e-05, grad_fn=<MseLossBackward0>)
epoch: 7848 loss: tensor(8.7654e-05, grad_fn=<MseLossBackward0>)
epoch: 7849 loss: tensor(8.7703e-05, grad_fn=<MseLossBackward0>)
epoch: 7850 loss: tensor(

epoch: 7984 loss: tensor(9.0618e-05, grad_fn=<MseLossBackward0>)
epoch: 7985 loss: tensor(8.7815e-05, grad_fn=<MseLossBackward0>)
epoch: 7986 loss: tensor(8.6747e-05, grad_fn=<MseLossBackward0>)
epoch: 7987 loss: tensor(8.7372e-05, grad_fn=<MseLossBackward0>)
epoch: 7988 loss: tensor(8.8921e-05, grad_fn=<MseLossBackward0>)
epoch: 7989 loss: tensor(9.0386e-05, grad_fn=<MseLossBackward0>)
epoch: 7990 loss: tensor(9.0966e-05, grad_fn=<MseLossBackward0>)
epoch: 7991 loss: tensor(9.0388e-05, grad_fn=<MseLossBackward0>)
epoch: 7992 loss: tensor(8.8989e-05, grad_fn=<MseLossBackward0>)
epoch: 7993 loss: tensor(8.7491e-05, grad_fn=<MseLossBackward0>)
epoch: 7994 loss: tensor(8.6569e-05, grad_fn=<MseLossBackward0>)
epoch: 7995 loss: tensor(8.6502e-05, grad_fn=<MseLossBackward0>)
epoch: 7996 loss: tensor(8.7092e-05, grad_fn=<MseLossBackward0>)
epoch: 7997 loss: tensor(8.7855e-05, grad_fn=<MseLossBackward0>)
epoch: 7998 loss: tensor(8.8319e-05, grad_fn=<MseLossBackward0>)
epoch: 7999 loss: tensor(

epoch: 8129 loss: tensor(9.5417e-05, grad_fn=<MseLossBackward0>)
epoch: 8130 loss: tensor(9.6813e-05, grad_fn=<MseLossBackward0>)
epoch: 8131 loss: tensor(9.7732e-05, grad_fn=<MseLossBackward0>)
epoch: 8132 loss: tensor(9.7383e-05, grad_fn=<MseLossBackward0>)
epoch: 8133 loss: tensor(9.5476e-05, grad_fn=<MseLossBackward0>)
epoch: 8134 loss: tensor(9.2461e-05, grad_fn=<MseLossBackward0>)
epoch: 8135 loss: tensor(8.9356e-05, grad_fn=<MseLossBackward0>)
epoch: 8136 loss: tensor(8.7210e-05, grad_fn=<MseLossBackward0>)
epoch: 8137 loss: tensor(8.6569e-05, grad_fn=<MseLossBackward0>)
epoch: 8138 loss: tensor(8.7284e-05, grad_fn=<MseLossBackward0>)
epoch: 8139 loss: tensor(8.8679e-05, grad_fn=<MseLossBackward0>)
epoch: 8140 loss: tensor(8.9928e-05, grad_fn=<MseLossBackward0>)
epoch: 8141 loss: tensor(9.0384e-05, grad_fn=<MseLossBackward0>)
epoch: 8142 loss: tensor(8.9852e-05, grad_fn=<MseLossBackward0>)
epoch: 8143 loss: tensor(8.8629e-05, grad_fn=<MseLossBackward0>)
epoch: 8144 loss: tensor(

epoch: 8275 loss: tensor(8.6391e-05, grad_fn=<MseLossBackward0>)
epoch: 8276 loss: tensor(8.6638e-05, grad_fn=<MseLossBackward0>)
epoch: 8277 loss: tensor(8.7018e-05, grad_fn=<MseLossBackward0>)
epoch: 8278 loss: tensor(8.7026e-05, grad_fn=<MseLossBackward0>)
epoch: 8279 loss: tensor(8.6574e-05, grad_fn=<MseLossBackward0>)
epoch: 8280 loss: tensor(8.6008e-05, grad_fn=<MseLossBackward0>)
epoch: 8281 loss: tensor(8.5745e-05, grad_fn=<MseLossBackward0>)
epoch: 8282 loss: tensor(8.5918e-05, grad_fn=<MseLossBackward0>)
epoch: 8283 loss: tensor(8.6304e-05, grad_fn=<MseLossBackward0>)
epoch: 8284 loss: tensor(8.6552e-05, grad_fn=<MseLossBackward0>)
epoch: 8285 loss: tensor(8.6482e-05, grad_fn=<MseLossBackward0>)
epoch: 8286 loss: tensor(8.6179e-05, grad_fn=<MseLossBackward0>)
epoch: 8287 loss: tensor(8.5879e-05, grad_fn=<MseLossBackward0>)
epoch: 8288 loss: tensor(8.5764e-05, grad_fn=<MseLossBackward0>)
epoch: 8289 loss: tensor(8.5832e-05, grad_fn=<MseLossBackward0>)
epoch: 8290 loss: tensor(

epoch: 8423 loss: tensor(8.5330e-05, grad_fn=<MseLossBackward0>)
epoch: 8424 loss: tensor(8.5331e-05, grad_fn=<MseLossBackward0>)
epoch: 8425 loss: tensor(8.5332e-05, grad_fn=<MseLossBackward0>)
epoch: 8426 loss: tensor(8.5331e-05, grad_fn=<MseLossBackward0>)
epoch: 8427 loss: tensor(8.5328e-05, grad_fn=<MseLossBackward0>)
epoch: 8428 loss: tensor(8.5324e-05, grad_fn=<MseLossBackward0>)
epoch: 8429 loss: tensor(8.5320e-05, grad_fn=<MseLossBackward0>)
epoch: 8430 loss: tensor(8.5315e-05, grad_fn=<MseLossBackward0>)
epoch: 8431 loss: tensor(8.5310e-05, grad_fn=<MseLossBackward0>)
epoch: 8432 loss: tensor(8.5306e-05, grad_fn=<MseLossBackward0>)
epoch: 8433 loss: tensor(8.5302e-05, grad_fn=<MseLossBackward0>)
epoch: 8434 loss: tensor(8.5299e-05, grad_fn=<MseLossBackward0>)
epoch: 8435 loss: tensor(8.5300e-05, grad_fn=<MseLossBackward0>)
epoch: 8436 loss: tensor(8.5301e-05, grad_fn=<MseLossBackward0>)
epoch: 8437 loss: tensor(8.5304e-05, grad_fn=<MseLossBackward0>)
epoch: 8438 loss: tensor(

epoch: 8570 loss: tensor(8.5004e-05, grad_fn=<MseLossBackward0>)
epoch: 8571 loss: tensor(8.5010e-05, grad_fn=<MseLossBackward0>)
epoch: 8572 loss: tensor(8.5019e-05, grad_fn=<MseLossBackward0>)
epoch: 8573 loss: tensor(8.5031e-05, grad_fn=<MseLossBackward0>)
epoch: 8574 loss: tensor(8.5050e-05, grad_fn=<MseLossBackward0>)
epoch: 8575 loss: tensor(8.5074e-05, grad_fn=<MseLossBackward0>)
epoch: 8576 loss: tensor(8.5106e-05, grad_fn=<MseLossBackward0>)
epoch: 8577 loss: tensor(8.5151e-05, grad_fn=<MseLossBackward0>)
epoch: 8578 loss: tensor(8.5211e-05, grad_fn=<MseLossBackward0>)
epoch: 8579 loss: tensor(8.5291e-05, grad_fn=<MseLossBackward0>)
epoch: 8580 loss: tensor(8.5399e-05, grad_fn=<MseLossBackward0>)
epoch: 8581 loss: tensor(8.5544e-05, grad_fn=<MseLossBackward0>)
epoch: 8582 loss: tensor(8.5739e-05, grad_fn=<MseLossBackward0>)
epoch: 8583 loss: tensor(8.6002e-05, grad_fn=<MseLossBackward0>)
epoch: 8584 loss: tensor(8.6355e-05, grad_fn=<MseLossBackward0>)
epoch: 8585 loss: tensor(

epoch: 8715 loss: tensor(8.5516e-05, grad_fn=<MseLossBackward0>)
epoch: 8716 loss: tensor(8.5458e-05, grad_fn=<MseLossBackward0>)
epoch: 8717 loss: tensor(8.5407e-05, grad_fn=<MseLossBackward0>)
epoch: 8718 loss: tensor(8.5363e-05, grad_fn=<MseLossBackward0>)
epoch: 8719 loss: tensor(8.5328e-05, grad_fn=<MseLossBackward0>)
epoch: 8720 loss: tensor(8.5298e-05, grad_fn=<MseLossBackward0>)
epoch: 8721 loss: tensor(8.5274e-05, grad_fn=<MseLossBackward0>)
epoch: 8722 loss: tensor(8.5255e-05, grad_fn=<MseLossBackward0>)
epoch: 8723 loss: tensor(8.5243e-05, grad_fn=<MseLossBackward0>)
epoch: 8724 loss: tensor(8.5239e-05, grad_fn=<MseLossBackward0>)
epoch: 8725 loss: tensor(8.5239e-05, grad_fn=<MseLossBackward0>)
epoch: 8726 loss: tensor(8.5246e-05, grad_fn=<MseLossBackward0>)
epoch: 8727 loss: tensor(8.5261e-05, grad_fn=<MseLossBackward0>)
epoch: 8728 loss: tensor(8.5284e-05, grad_fn=<MseLossBackward0>)
epoch: 8729 loss: tensor(8.5317e-05, grad_fn=<MseLossBackward0>)
epoch: 8730 loss: tensor(

epoch: 8861 loss: tensor(8.4920e-05, grad_fn=<MseLossBackward0>)
epoch: 8862 loss: tensor(8.4839e-05, grad_fn=<MseLossBackward0>)
epoch: 8863 loss: tensor(8.4818e-05, grad_fn=<MseLossBackward0>)
epoch: 8864 loss: tensor(8.4867e-05, grad_fn=<MseLossBackward0>)
epoch: 8865 loss: tensor(8.4959e-05, grad_fn=<MseLossBackward0>)
epoch: 8866 loss: tensor(8.5058e-05, grad_fn=<MseLossBackward0>)
epoch: 8867 loss: tensor(8.5125e-05, grad_fn=<MseLossBackward0>)
epoch: 8868 loss: tensor(8.5159e-05, grad_fn=<MseLossBackward0>)
epoch: 8869 loss: tensor(8.5178e-05, grad_fn=<MseLossBackward0>)
epoch: 8870 loss: tensor(8.5212e-05, grad_fn=<MseLossBackward0>)
epoch: 8871 loss: tensor(8.5284e-05, grad_fn=<MseLossBackward0>)
epoch: 8872 loss: tensor(8.5394e-05, grad_fn=<MseLossBackward0>)
epoch: 8873 loss: tensor(8.5533e-05, grad_fn=<MseLossBackward0>)
epoch: 8874 loss: tensor(8.5686e-05, grad_fn=<MseLossBackward0>)
epoch: 8875 loss: tensor(8.5840e-05, grad_fn=<MseLossBackward0>)
epoch: 8876 loss: tensor(

epoch: 9008 loss: tensor(8.4771e-05, grad_fn=<MseLossBackward0>)
epoch: 9009 loss: tensor(8.4481e-05, grad_fn=<MseLossBackward0>)
epoch: 9010 loss: tensor(8.4203e-05, grad_fn=<MseLossBackward0>)
epoch: 9011 loss: tensor(8.3999e-05, grad_fn=<MseLossBackward0>)
epoch: 9012 loss: tensor(8.3902e-05, grad_fn=<MseLossBackward0>)
epoch: 9013 loss: tensor(8.3911e-05, grad_fn=<MseLossBackward0>)
epoch: 9014 loss: tensor(8.3998e-05, grad_fn=<MseLossBackward0>)
epoch: 9015 loss: tensor(8.4119e-05, grad_fn=<MseLossBackward0>)
epoch: 9016 loss: tensor(8.4229e-05, grad_fn=<MseLossBackward0>)
epoch: 9017 loss: tensor(8.4300e-05, grad_fn=<MseLossBackward0>)
epoch: 9018 loss: tensor(8.4315e-05, grad_fn=<MseLossBackward0>)
epoch: 9019 loss: tensor(8.4277e-05, grad_fn=<MseLossBackward0>)
epoch: 9020 loss: tensor(8.4198e-05, grad_fn=<MseLossBackward0>)
epoch: 9021 loss: tensor(8.4099e-05, grad_fn=<MseLossBackward0>)
epoch: 9022 loss: tensor(8.3999e-05, grad_fn=<MseLossBackward0>)
epoch: 9023 loss: tensor(

epoch: 9157 loss: tensor(8.3735e-05, grad_fn=<MseLossBackward0>)
epoch: 9158 loss: tensor(8.4200e-05, grad_fn=<MseLossBackward0>)
epoch: 9159 loss: tensor(8.5010e-05, grad_fn=<MseLossBackward0>)
epoch: 9160 loss: tensor(8.5776e-05, grad_fn=<MseLossBackward0>)
epoch: 9161 loss: tensor(8.6200e-05, grad_fn=<MseLossBackward0>)
epoch: 9162 loss: tensor(8.6142e-05, grad_fn=<MseLossBackward0>)
epoch: 9163 loss: tensor(8.5649e-05, grad_fn=<MseLossBackward0>)
epoch: 9164 loss: tensor(8.4922e-05, grad_fn=<MseLossBackward0>)
epoch: 9165 loss: tensor(8.4220e-05, grad_fn=<MseLossBackward0>)
epoch: 9166 loss: tensor(8.3748e-05, grad_fn=<MseLossBackward0>)
epoch: 9167 loss: tensor(8.3600e-05, grad_fn=<MseLossBackward0>)
epoch: 9168 loss: tensor(8.3735e-05, grad_fn=<MseLossBackward0>)
epoch: 9169 loss: tensor(8.4023e-05, grad_fn=<MseLossBackward0>)
epoch: 9170 loss: tensor(8.4312e-05, grad_fn=<MseLossBackward0>)
epoch: 9171 loss: tensor(8.4484e-05, grad_fn=<MseLossBackward0>)
epoch: 9172 loss: tensor(

epoch: 9304 loss: tensor(8.3729e-05, grad_fn=<MseLossBackward0>)
epoch: 9305 loss: tensor(8.3573e-05, grad_fn=<MseLossBackward0>)
epoch: 9306 loss: tensor(8.3463e-05, grad_fn=<MseLossBackward0>)
epoch: 9307 loss: tensor(8.3385e-05, grad_fn=<MseLossBackward0>)
epoch: 9308 loss: tensor(8.3327e-05, grad_fn=<MseLossBackward0>)
epoch: 9309 loss: tensor(8.3288e-05, grad_fn=<MseLossBackward0>)
epoch: 9310 loss: tensor(8.3269e-05, grad_fn=<MseLossBackward0>)
epoch: 9311 loss: tensor(8.3272e-05, grad_fn=<MseLossBackward0>)
epoch: 9312 loss: tensor(8.3298e-05, grad_fn=<MseLossBackward0>)
epoch: 9313 loss: tensor(8.3347e-05, grad_fn=<MseLossBackward0>)
epoch: 9314 loss: tensor(8.3410e-05, grad_fn=<MseLossBackward0>)
epoch: 9315 loss: tensor(8.3483e-05, grad_fn=<MseLossBackward0>)
epoch: 9316 loss: tensor(8.3555e-05, grad_fn=<MseLossBackward0>)
epoch: 9317 loss: tensor(8.3618e-05, grad_fn=<MseLossBackward0>)
epoch: 9318 loss: tensor(8.3665e-05, grad_fn=<MseLossBackward0>)
epoch: 9319 loss: tensor(

epoch: 9450 loss: tensor(8.3190e-05, grad_fn=<MseLossBackward0>)
epoch: 9451 loss: tensor(8.3125e-05, grad_fn=<MseLossBackward0>)
epoch: 9452 loss: tensor(8.3073e-05, grad_fn=<MseLossBackward0>)
epoch: 9453 loss: tensor(8.3059e-05, grad_fn=<MseLossBackward0>)
epoch: 9454 loss: tensor(8.3098e-05, grad_fn=<MseLossBackward0>)
epoch: 9455 loss: tensor(8.3200e-05, grad_fn=<MseLossBackward0>)
epoch: 9456 loss: tensor(8.3365e-05, grad_fn=<MseLossBackward0>)
epoch: 9457 loss: tensor(8.3598e-05, grad_fn=<MseLossBackward0>)
epoch: 9458 loss: tensor(8.3901e-05, grad_fn=<MseLossBackward0>)
epoch: 9459 loss: tensor(8.4292e-05, grad_fn=<MseLossBackward0>)
epoch: 9460 loss: tensor(8.4804e-05, grad_fn=<MseLossBackward0>)
epoch: 9461 loss: tensor(8.5480e-05, grad_fn=<MseLossBackward0>)
epoch: 9462 loss: tensor(8.6373e-05, grad_fn=<MseLossBackward0>)
epoch: 9463 loss: tensor(8.7520e-05, grad_fn=<MseLossBackward0>)
epoch: 9464 loss: tensor(8.8935e-05, grad_fn=<MseLossBackward0>)
epoch: 9465 loss: tensor(

epoch: 9593 loss: tensor(8.2484e-05, grad_fn=<MseLossBackward0>)
epoch: 9594 loss: tensor(8.2491e-05, grad_fn=<MseLossBackward0>)
epoch: 9595 loss: tensor(8.2509e-05, grad_fn=<MseLossBackward0>)
epoch: 9596 loss: tensor(8.2526e-05, grad_fn=<MseLossBackward0>)
epoch: 9597 loss: tensor(8.2537e-05, grad_fn=<MseLossBackward0>)
epoch: 9598 loss: tensor(8.2540e-05, grad_fn=<MseLossBackward0>)
epoch: 9599 loss: tensor(8.2539e-05, grad_fn=<MseLossBackward0>)
epoch: 9600 loss: tensor(8.2542e-05, grad_fn=<MseLossBackward0>)
epoch: 9601 loss: tensor(8.2555e-05, grad_fn=<MseLossBackward0>)
epoch: 9602 loss: tensor(8.2585e-05, grad_fn=<MseLossBackward0>)
epoch: 9603 loss: tensor(8.2643e-05, grad_fn=<MseLossBackward0>)
epoch: 9604 loss: tensor(8.2730e-05, grad_fn=<MseLossBackward0>)
epoch: 9605 loss: tensor(8.2866e-05, grad_fn=<MseLossBackward0>)
epoch: 9606 loss: tensor(8.3065e-05, grad_fn=<MseLossBackward0>)
epoch: 9607 loss: tensor(8.3363e-05, grad_fn=<MseLossBackward0>)
epoch: 9608 loss: tensor(

epoch: 9741 loss: tensor(8.2794e-05, grad_fn=<MseLossBackward0>)
epoch: 9742 loss: tensor(8.2603e-05, grad_fn=<MseLossBackward0>)
epoch: 9743 loss: tensor(8.2338e-05, grad_fn=<MseLossBackward0>)
epoch: 9744 loss: tensor(8.2157e-05, grad_fn=<MseLossBackward0>)
epoch: 9745 loss: tensor(8.2143e-05, grad_fn=<MseLossBackward0>)
epoch: 9746 loss: tensor(8.2257e-05, grad_fn=<MseLossBackward0>)
epoch: 9747 loss: tensor(8.2389e-05, grad_fn=<MseLossBackward0>)
epoch: 9748 loss: tensor(8.2446e-05, grad_fn=<MseLossBackward0>)
epoch: 9749 loss: tensor(8.2393e-05, grad_fn=<MseLossBackward0>)
epoch: 9750 loss: tensor(8.2271e-05, grad_fn=<MseLossBackward0>)
epoch: 9751 loss: tensor(8.2155e-05, grad_fn=<MseLossBackward0>)
epoch: 9752 loss: tensor(8.2099e-05, grad_fn=<MseLossBackward0>)
epoch: 9753 loss: tensor(8.2119e-05, grad_fn=<MseLossBackward0>)
epoch: 9754 loss: tensor(8.2178e-05, grad_fn=<MseLossBackward0>)
epoch: 9755 loss: tensor(8.2230e-05, grad_fn=<MseLossBackward0>)
epoch: 9756 loss: tensor(

epoch: 9887 loss: tensor(9.0447e-05, grad_fn=<MseLossBackward0>)
epoch: 9888 loss: tensor(8.9100e-05, grad_fn=<MseLossBackward0>)
epoch: 9889 loss: tensor(8.7061e-05, grad_fn=<MseLossBackward0>)
epoch: 9890 loss: tensor(8.4822e-05, grad_fn=<MseLossBackward0>)
epoch: 9891 loss: tensor(8.2985e-05, grad_fn=<MseLossBackward0>)
epoch: 9892 loss: tensor(8.1975e-05, grad_fn=<MseLossBackward0>)
epoch: 9893 loss: tensor(8.1885e-05, grad_fn=<MseLossBackward0>)
epoch: 9894 loss: tensor(8.2483e-05, grad_fn=<MseLossBackward0>)
epoch: 9895 loss: tensor(8.3366e-05, grad_fn=<MseLossBackward0>)
epoch: 9896 loss: tensor(8.4128e-05, grad_fn=<MseLossBackward0>)
epoch: 9897 loss: tensor(8.4477e-05, grad_fn=<MseLossBackward0>)
epoch: 9898 loss: tensor(8.4313e-05, grad_fn=<MseLossBackward0>)
epoch: 9899 loss: tensor(8.3734e-05, grad_fn=<MseLossBackward0>)
epoch: 9900 loss: tensor(8.2979e-05, grad_fn=<MseLossBackward0>)
epoch: 9901 loss: tensor(8.2316e-05, grad_fn=<MseLossBackward0>)
epoch: 9902 loss: tensor(

In [148]:
#net = net.to(device)
N_epochs = 10000

labels_temp = np.array(labels_temp)
#train_data_torch = torch.from_numpy(features_temp).float()
#train_target_torch = torch.from_numpy(labels_temp).float()
train_target_torch = torch.tensor(torch.from_numpy(np.array(labels_temp)).float())

import sys
np.set_printoptions(threshold=sys.maxsize)

def validate(net, test_data, test_target, i):
    
    test_data_torch = torch.from_numpy(features_test).float()
    #test_target_torch = torch.from_numpy(labels_test).float()
    test_target_torch = torch.tensor(torch.from_numpy(np.array(test_target)).float())

    test_pred = np.rint(net(test_data_torch).detach().numpy())
    if i % 500 == 0:
        print(np.concatenate((test_pred, test_target_torch.detach().numpy()), axis=1))
    #test_accuracy = (test_target_torch.detach().numpy() == test_pred).float().mean().detach().numpy()
    test_accuracy = (test_target_torch.detach().numpy() == test_pred).mean()

    #test_rmse = ((test_pred-test_target_torch)**2).mean().sqrt().detach().numpy()
    test_rmse = (np.sqrt((test_pred-test_target_torch.detach().numpy())**2).mean())

    return test_accuracy, test_rmse

for i in range(1):
    #pred = net(train_data_torch)
    #loss = criterion(pred, train_target_torch)
    
    #optimizer.zero_grad()
    #loss.backward()
    #optimizer.step()
    
    if i % 100 == 0:
        #train_accuracy, train_rmse = validate(net, features_temp, labels_temp)
        test_accuracy, test_rmse = validate(net, features_test, labels_test, i)
        #print(f'Epoch = {i} loss={loss} train_acc = {train_accuracy:.3f} test_acc = {test_accuracy:.3f} train_rmse = {train_rmse:.3f}  test_rmse = {test_rmse:.3f}')         
        print(f'Epoch = {i} test_acc = {test_accuracy:.3f}  test_rmse = {test_rmse:.3f}') 

[[ 0.  2.  0.  2.]
 [ 1.  2.  1.  2.]
 [ 3.  2.  3.  2.]
 [ 5.  2.  5.  2.]
 [ 8.  2.  8.  2.]
 [ 9.  2.  9.  2.]
 [10.  2. 10.  2.]
 [11.  2. 11.  2.]
 [12.  2. 12.  2.]
 [13.  2. 13.  2.]
 [14.  2. 14.  2.]
 [15.  2. 15.  2.]
 [16.  2. 16.  2.]
 [17.  2. 17.  2.]
 [ 3.  2.  3.  2.]
 [ 5.  2.  5.  2.]
 [ 8.  2.  8.  2.]
 [ 9.  2.  9.  2.]
 [10.  2. 10.  2.]
 [11.  2. 11.  2.]
 [12.  2. 12.  2.]
 [13.  2. 13.  2.]
 [14.  2. 14.  2.]
 [15.  2. 15.  2.]
 [16.  2. 16.  2.]
 [17.  2. 17.  2.]
 [ 3.  2.  3.  2.]
 [ 5.  2.  5.  2.]
 [ 8.  2.  8.  2.]
 [ 9.  2.  9.  2.]
 [10.  2. 10.  2.]
 [11.  2. 11.  2.]
 [12.  2. 12.  2.]
 [13.  2. 13.  2.]
 [14.  2. 14.  2.]
 [15.  2. 15.  2.]
 [16.  2. 16.  2.]
 [17.  2. 17.  2.]
 [ 3.  2.  3.  2.]
 [ 5.  2.  5.  2.]
 [ 8.  2.  8.  2.]
 [ 9.  2.  9.  2.]
 [10.  2. 10.  2.]
 [11.  2. 11.  2.]
 [12.  2. 12.  2.]
 [13.  2. 13.  2.]
 [14.  2. 14.  2.]
 [15.  2. 15.  2.]
 [16.  2. 16.  2.]
 [17.  2. 17.  2.]
 [ 3.  2.  3.  2.]
 [ 5.  2.  5.  2.]
 [ 8.  2.  8

/tmp/ipykernel_39771/3030192740.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  train_target_torch = torch.tensor(torch.from_numpy(np.array(labels_temp)).float())
/tmp/ipykernel_39771/3030192740.py:16: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_target_torch = torch.tensor(torch.from_numpy(np.array(test_target)).float())


In [134]:
preds = net(torch.from_numpy(features_test[3]).float()).detach().numpy()
print(np.rint(preds))

[5. 2.]


In [67]:
for p in preds:
    print(p)

tensor(4.9992, grad_fn=<UnbindBackward0>)
tensor(2.0004, grad_fn=<UnbindBackward0>)


In [60]:
labels_test[3]

array([5, 2], dtype=uint8)