## Preparing SV Dataset

In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pylab as plt

#np.set_printoptions(formatter={'int':hex})

import os
files = os.listdir('sv_traces/')

### reads an sv_trace file into 2 structures:
### pcs: a list of 1001 16-bit pc values
### mem: a list of 1001 65542-byte memory vectors
def read_trace(sv_file):
    with open(sv_file, 'rb') as f:
        lines = f.read()
        lines = np.frombuffer(lines, dtype=np.uint8)
        lines = lines.reshape(1001,-1)
        pcs = lines[:, 0:2]
        mem = lines[:, :]
        #pcs = [np.uint16(i[1]<<8 | i[0]) for i in pcs]
        return mem, pcs
    
### reads trace data into a dataset of mem-to-pc mappings, where
### mem_current: partial memory trace &
### pcs_current: full pcs trace
def read_dataset(file):
    mem_trace = dict_traces[file][0]
    mem_current = mem_trace[:]
    pcs_trace = dict_traces[file][1]
    pcs_current = pcs_trace[:]
    return mem_current, pcs_current

### dict_traces[file][0]: memory trace of <file>
### dict_traces[file][1]: pc trace of <file>
dict_traces = {}
for file in files[0:20]:
    dict_traces[file] = read_trace(os.path.join('sv_traces/', file))
    
### dict_dataset[file][0]: memory trace of <file>
### dict_dataset[file][1]: pc trace of <file>
dict_dataset = {}
for trace in dict_traces:
    dict_dataset[trace] = read_dataset(trace)

In [2]:
dict_traces

{'167:149:9.svbinttrc': (array([[  0,   2,   0, ...,   2,   0,   0],
         [  1,   2,   0, ...,   2,   0,   0],
         [  3,   2,   0, ...,   2,   0,   0],
         ...,
         [  3,   2, 126, ...,   2,   0,   0],
         [  5,   2,  20, ...,   2,   0,   0],
         [  7,   2,  20, ...,   2,   0,   0]], dtype=uint8),
  array([[0, 2],
         [1, 2],
         [3, 2],
         ...,
         [3, 2],
         [5, 2],
         [7, 2]], dtype=uint8)),
 '121:187:13.svbinttrc': (array([[ 0,  2,  0, ...,  2,  0,  0],
         [ 1,  2,  0, ...,  2,  0,  0],
         [ 3,  2,  0, ...,  2,  0,  0],
         ...,
         [ 9,  2, 50, ...,  2,  0,  0],
         [10,  2, 50, ...,  2,  0,  0],
         [11,  2, 50, ...,  2,  0,  0]], dtype=uint8),
  array([[ 0,  2],
         [ 1,  2],
         [ 3,  2],
         ...,
         [ 9,  2],
         [10,  2],
         [11,  2]], dtype=uint8)),
 '144:101:13.svbinttrc': (array([[  0,   2,   0, ...,   2,   0,   0],
         [  1,   2,   0, ...,   2

In [4]:
dict_dataset

{'167:149:9.svbinttrc': (array([[  0,   2,   0, ...,   2,   0,   0],
         [  1,   2,   0, ...,   2,   0,   0],
         [  3,   2,   0, ...,   2,   0,   0],
         ...,
         [  3,   2, 126, ...,   2,   0,   0],
         [  5,   2,  20, ...,   2,   0,   0],
         [  7,   2,  20, ...,   2,   0,   0]], dtype=uint8),
  array([[0, 2],
         [1, 2],
         [3, 2],
         ...,
         [3, 2],
         [5, 2],
         [7, 2]], dtype=uint8)),
 '121:187:13.svbinttrc': (array([[ 0,  2,  0, ...,  2,  0,  0],
         [ 1,  2,  0, ...,  2,  0,  0],
         [ 3,  2,  0, ...,  2,  0,  0],
         ...,
         [ 9,  2, 50, ...,  2,  0,  0],
         [10,  2, 50, ...,  2,  0,  0],
         [11,  2, 50, ...,  2,  0,  0]], dtype=uint8),
  array([[ 0,  2],
         [ 1,  2],
         [ 3,  2],
         ...,
         [ 9,  2],
         [10,  2],
         [11,  2]], dtype=uint8)),
 '144:101:13.svbinttrc': (array([[  0,   2,   0, ...,   2,   0,   0],
         [  1,   2,   0, ...,   2

## Defining Neural Net

In [3]:
import torch
import torch.nn as nn
import torch.optim as optim

In [4]:
def format_label(l, width=16):
    val = bin(l)[2:]
    N = len(val)
    return [0.] * (width-N) + [float(i) for i in val]

In [5]:
format_label(512)

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0]

In [6]:
features, labels = dict_dataset[list(dict_dataset.keys())[0]]
for file in list(dict_dataset.keys())[1:10]:
    features = np.append(features, dict_dataset[file][0], axis=0)
    labels = np.append(labels, dict_dataset[file][1], axis=0)

features_test, labels_test = dict_dataset[list(dict_dataset.keys())[10]]
for file in list(dict_dataset.keys())[11:13]:
    features_test = np.append(features_test, dict_dataset[file][0], axis=0)
    labels_test = np.append(labels_test, dict_dataset[file][1], axis=0)

In [9]:
#features, labels = dict_dataset[list(dict_dataset.keys())[0]]
#features_test, labels_test = dict_dataset[list(dict_dataset.keys())[1]]
#features = features - features.mean(axis=0)
# temp
features_temp = features#[9:15, ]
labels_temp = labels#[9:15]
# end temp

In [9]:
print(labels_test[0:16])
print(labels_temp[0:16])


[[ 0  2]
 [ 1  2]
 [ 3  2]
 [ 5  2]
 [ 8  2]
 [ 9  2]
 [10  2]
 [11  2]
 [12  2]
 [13  2]
 [14  2]
 [15  2]
 [16  2]
 [17  2]
 [ 3  2]
 [ 5  2]]
[[ 0  2]
 [ 1  2]
 [ 3  2]
 [ 5  2]
 [ 7  2]
 [ 8  2]
 [ 9  2]
 [10  2]
 [11  2]
 [12  2]
 [13  2]
 [14  2]
 [15  2]
 [16  2]
 [ 3  2]
 [ 5  2]]


In [10]:
labels_temp[2]

array([3, 2], dtype=uint8)

In [11]:
partial_mem_trace = features_temp[: , 0:600]
#partial_mem_trace = features_temp[: , 0:1024]
features_temp = partial_mem_trace # all rows are identical here

partial_mem_trace_test = features_test[: , 0:600]
#partial_mem_trace_test = features_test[: , 0:1024]
features_test = partial_mem_trace_test # all rows are identical here

    
print(partial_mem_trace.shape[0])
print(features_temp.shape[0])
print(partial_mem_trace.shape[1])
print(features_temp.shape[1])

10010
10010
600
600


In [12]:
features_temp[0]

array([  0,   2,   0,   0,   0,   0,  20,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

### Training NN

In [33]:
net = nn.Sequential(
    nn.Linear(features_temp.shape[1], 2**8),
    nn.ReLU(), #rectified linear unit
    nn.Linear(2**8, 2**12),
    nn.ReLU(),
    #nn.Linear(2**8, 2**4),
    #nn.ReLU(),
    nn.Linear(2**12, 2),
    #nn.Sigmoid()
)

#criterion = nn.BCELoss()
#criterion = nn.CrossEntropyLoss()
criterion = nn.MSELoss()

def train(n_epochs, net, features, labels, criterion, optimizer, freq=1, debug=False):
    for i in range(n_epochs): #number of passes over full dataset
        #step 1: get features and use net to make predictions
        preds = net(torch.from_numpy(features).float())
        
        #step 2: compute loss/error
        labels_torch = torch.tensor(torch.from_numpy(np.array(labels)).float())
        if debug: print('\n------')
        if debug: print(preds)
        #loss = np.sqrt(((np.rint(preds.detach().numpy()) - labels_torch.detach().numpy())**2).mean())
        loss = criterion(preds, labels_torch)
        if i % freq == 0:
            print('epoch:', i, 'loss:', loss)

        #step 3: backprop to update weights
        # compute gradients/derivatives - backprop
        # use gradients to update weights - gradient descent - w = w - 0.1 * deriv. loss w.r.t. w

        optimizer.zero_grad() #set previous buffers to zero
        loss.backward() #backprop
        optimizer.step() #update weights        
        
    return net

optimizer = optim.Adam(net.parameters(), lr=1e-6)
print(features_temp)
#net = train(1000, net, features_temp, labels_temp, criterion, optimizer, debug=False)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [34]:
optimizer = optim.Adam(net.parameters(), lr=1e-5)

In [35]:
net = train(5000, net, features_temp, labels_temp, criterion, optimizer, debug=False)

/tmp/ipykernel_109417/2880589121.py:22: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels_torch = torch.tensor(torch.from_numpy(np.array(labels)).float())


epoch: 0 loss: tensor(95.9756, grad_fn=<MseLossBackward0>)
epoch: 1 loss: tensor(89.6505, grad_fn=<MseLossBackward0>)
epoch: 2 loss: tensor(83.5865, grad_fn=<MseLossBackward0>)
epoch: 3 loss: tensor(77.7861, grad_fn=<MseLossBackward0>)
epoch: 4 loss: tensor(72.2498, grad_fn=<MseLossBackward0>)
epoch: 5 loss: tensor(66.9761, grad_fn=<MseLossBackward0>)
epoch: 6 loss: tensor(61.9637, grad_fn=<MseLossBackward0>)
epoch: 7 loss: tensor(57.2113, grad_fn=<MseLossBackward0>)
epoch: 8 loss: tensor(52.7171, grad_fn=<MseLossBackward0>)
epoch: 9 loss: tensor(48.4797, grad_fn=<MseLossBackward0>)
epoch: 10 loss: tensor(44.4979, grad_fn=<MseLossBackward0>)
epoch: 11 loss: tensor(40.7705, grad_fn=<MseLossBackward0>)
epoch: 12 loss: tensor(37.2952, grad_fn=<MseLossBackward0>)
epoch: 13 loss: tensor(34.0690, grad_fn=<MseLossBackward0>)
epoch: 14 loss: tensor(31.0885, grad_fn=<MseLossBackward0>)
epoch: 15 loss: tensor(28.3491, grad_fn=<MseLossBackward0>)
epoch: 16 loss: tensor(25.8450, grad_fn=<MseLossBa

epoch: 138 loss: tensor(8.7595, grad_fn=<MseLossBackward0>)
epoch: 139 loss: tensor(8.7577, grad_fn=<MseLossBackward0>)
epoch: 140 loss: tensor(8.7558, grad_fn=<MseLossBackward0>)
epoch: 141 loss: tensor(8.7539, grad_fn=<MseLossBackward0>)
epoch: 142 loss: tensor(8.7521, grad_fn=<MseLossBackward0>)
epoch: 143 loss: tensor(8.7502, grad_fn=<MseLossBackward0>)
epoch: 144 loss: tensor(8.7484, grad_fn=<MseLossBackward0>)
epoch: 145 loss: tensor(8.7466, grad_fn=<MseLossBackward0>)
epoch: 146 loss: tensor(8.7448, grad_fn=<MseLossBackward0>)
epoch: 147 loss: tensor(8.7430, grad_fn=<MseLossBackward0>)
epoch: 148 loss: tensor(8.7412, grad_fn=<MseLossBackward0>)
epoch: 149 loss: tensor(8.7394, grad_fn=<MseLossBackward0>)
epoch: 150 loss: tensor(8.7377, grad_fn=<MseLossBackward0>)
epoch: 151 loss: tensor(8.7359, grad_fn=<MseLossBackward0>)
epoch: 152 loss: tensor(8.7342, grad_fn=<MseLossBackward0>)
epoch: 153 loss: tensor(8.7325, grad_fn=<MseLossBackward0>)
epoch: 154 loss: tensor(8.7308, grad_fn=

epoch: 275 loss: tensor(8.5471, grad_fn=<MseLossBackward0>)
epoch: 276 loss: tensor(8.5456, grad_fn=<MseLossBackward0>)
epoch: 277 loss: tensor(8.5440, grad_fn=<MseLossBackward0>)
epoch: 278 loss: tensor(8.5425, grad_fn=<MseLossBackward0>)
epoch: 279 loss: tensor(8.5409, grad_fn=<MseLossBackward0>)
epoch: 280 loss: tensor(8.5394, grad_fn=<MseLossBackward0>)
epoch: 281 loss: tensor(8.5378, grad_fn=<MseLossBackward0>)
epoch: 282 loss: tensor(8.5362, grad_fn=<MseLossBackward0>)
epoch: 283 loss: tensor(8.5347, grad_fn=<MseLossBackward0>)
epoch: 284 loss: tensor(8.5331, grad_fn=<MseLossBackward0>)
epoch: 285 loss: tensor(8.5316, grad_fn=<MseLossBackward0>)
epoch: 286 loss: tensor(8.5300, grad_fn=<MseLossBackward0>)
epoch: 287 loss: tensor(8.5284, grad_fn=<MseLossBackward0>)
epoch: 288 loss: tensor(8.5269, grad_fn=<MseLossBackward0>)
epoch: 289 loss: tensor(8.5253, grad_fn=<MseLossBackward0>)
epoch: 290 loss: tensor(8.5238, grad_fn=<MseLossBackward0>)
epoch: 291 loss: tensor(8.5222, grad_fn=

epoch: 412 loss: tensor(8.3316, grad_fn=<MseLossBackward0>)
epoch: 413 loss: tensor(8.3300, grad_fn=<MseLossBackward0>)
epoch: 414 loss: tensor(8.3284, grad_fn=<MseLossBackward0>)
epoch: 415 loss: tensor(8.3269, grad_fn=<MseLossBackward0>)
epoch: 416 loss: tensor(8.3253, grad_fn=<MseLossBackward0>)
epoch: 417 loss: tensor(8.3237, grad_fn=<MseLossBackward0>)
epoch: 418 loss: tensor(8.3222, grad_fn=<MseLossBackward0>)
epoch: 419 loss: tensor(8.3206, grad_fn=<MseLossBackward0>)
epoch: 420 loss: tensor(8.3190, grad_fn=<MseLossBackward0>)
epoch: 421 loss: tensor(8.3175, grad_fn=<MseLossBackward0>)
epoch: 422 loss: tensor(8.3159, grad_fn=<MseLossBackward0>)
epoch: 423 loss: tensor(8.3143, grad_fn=<MseLossBackward0>)
epoch: 424 loss: tensor(8.3127, grad_fn=<MseLossBackward0>)
epoch: 425 loss: tensor(8.3111, grad_fn=<MseLossBackward0>)
epoch: 426 loss: tensor(8.3095, grad_fn=<MseLossBackward0>)
epoch: 427 loss: tensor(8.3080, grad_fn=<MseLossBackward0>)
epoch: 428 loss: tensor(8.3064, grad_fn=

epoch: 549 loss: tensor(8.0917, grad_fn=<MseLossBackward0>)
epoch: 550 loss: tensor(8.0898, grad_fn=<MseLossBackward0>)
epoch: 551 loss: tensor(8.0879, grad_fn=<MseLossBackward0>)
epoch: 552 loss: tensor(8.0860, grad_fn=<MseLossBackward0>)
epoch: 553 loss: tensor(8.0841, grad_fn=<MseLossBackward0>)
epoch: 554 loss: tensor(8.0822, grad_fn=<MseLossBackward0>)
epoch: 555 loss: tensor(8.0803, grad_fn=<MseLossBackward0>)
epoch: 556 loss: tensor(8.0784, grad_fn=<MseLossBackward0>)
epoch: 557 loss: tensor(8.0764, grad_fn=<MseLossBackward0>)
epoch: 558 loss: tensor(8.0745, grad_fn=<MseLossBackward0>)
epoch: 559 loss: tensor(8.0726, grad_fn=<MseLossBackward0>)
epoch: 560 loss: tensor(8.0706, grad_fn=<MseLossBackward0>)
epoch: 561 loss: tensor(8.0687, grad_fn=<MseLossBackward0>)
epoch: 562 loss: tensor(8.0668, grad_fn=<MseLossBackward0>)
epoch: 563 loss: tensor(8.0648, grad_fn=<MseLossBackward0>)
epoch: 564 loss: tensor(8.0629, grad_fn=<MseLossBackward0>)
epoch: 565 loss: tensor(8.0609, grad_fn=

epoch: 686 loss: tensor(7.7928, grad_fn=<MseLossBackward0>)
epoch: 687 loss: tensor(7.7903, grad_fn=<MseLossBackward0>)
epoch: 688 loss: tensor(7.7877, grad_fn=<MseLossBackward0>)
epoch: 689 loss: tensor(7.7851, grad_fn=<MseLossBackward0>)
epoch: 690 loss: tensor(7.7825, grad_fn=<MseLossBackward0>)
epoch: 691 loss: tensor(7.7798, grad_fn=<MseLossBackward0>)
epoch: 692 loss: tensor(7.7772, grad_fn=<MseLossBackward0>)
epoch: 693 loss: tensor(7.7746, grad_fn=<MseLossBackward0>)
epoch: 694 loss: tensor(7.7720, grad_fn=<MseLossBackward0>)
epoch: 695 loss: tensor(7.7693, grad_fn=<MseLossBackward0>)
epoch: 696 loss: tensor(7.7668, grad_fn=<MseLossBackward0>)
epoch: 697 loss: tensor(7.7642, grad_fn=<MseLossBackward0>)
epoch: 698 loss: tensor(7.7616, grad_fn=<MseLossBackward0>)
epoch: 699 loss: tensor(7.7590, grad_fn=<MseLossBackward0>)
epoch: 700 loss: tensor(7.7564, grad_fn=<MseLossBackward0>)
epoch: 701 loss: tensor(7.7537, grad_fn=<MseLossBackward0>)
epoch: 702 loss: tensor(7.7511, grad_fn=

epoch: 823 loss: tensor(7.4031, grad_fn=<MseLossBackward0>)
epoch: 824 loss: tensor(7.3999, grad_fn=<MseLossBackward0>)
epoch: 825 loss: tensor(7.3967, grad_fn=<MseLossBackward0>)
epoch: 826 loss: tensor(7.3935, grad_fn=<MseLossBackward0>)
epoch: 827 loss: tensor(7.3903, grad_fn=<MseLossBackward0>)
epoch: 828 loss: tensor(7.3871, grad_fn=<MseLossBackward0>)
epoch: 829 loss: tensor(7.3839, grad_fn=<MseLossBackward0>)
epoch: 830 loss: tensor(7.3807, grad_fn=<MseLossBackward0>)
epoch: 831 loss: tensor(7.3774, grad_fn=<MseLossBackward0>)
epoch: 832 loss: tensor(7.3742, grad_fn=<MseLossBackward0>)
epoch: 833 loss: tensor(7.3709, grad_fn=<MseLossBackward0>)
epoch: 834 loss: tensor(7.3676, grad_fn=<MseLossBackward0>)
epoch: 835 loss: tensor(7.3642, grad_fn=<MseLossBackward0>)
epoch: 836 loss: tensor(7.3609, grad_fn=<MseLossBackward0>)
epoch: 837 loss: tensor(7.3575, grad_fn=<MseLossBackward0>)
epoch: 838 loss: tensor(7.3542, grad_fn=<MseLossBackward0>)
epoch: 839 loss: tensor(7.3510, grad_fn=

epoch: 960 loss: tensor(6.8842, grad_fn=<MseLossBackward0>)
epoch: 961 loss: tensor(6.8795, grad_fn=<MseLossBackward0>)
epoch: 962 loss: tensor(6.8747, grad_fn=<MseLossBackward0>)
epoch: 963 loss: tensor(6.8698, grad_fn=<MseLossBackward0>)
epoch: 964 loss: tensor(6.8649, grad_fn=<MseLossBackward0>)
epoch: 965 loss: tensor(6.8601, grad_fn=<MseLossBackward0>)
epoch: 966 loss: tensor(6.8554, grad_fn=<MseLossBackward0>)
epoch: 967 loss: tensor(6.8507, grad_fn=<MseLossBackward0>)
epoch: 968 loss: tensor(6.8460, grad_fn=<MseLossBackward0>)
epoch: 969 loss: tensor(6.8414, grad_fn=<MseLossBackward0>)
epoch: 970 loss: tensor(6.8367, grad_fn=<MseLossBackward0>)
epoch: 971 loss: tensor(6.8321, grad_fn=<MseLossBackward0>)
epoch: 972 loss: tensor(6.8274, grad_fn=<MseLossBackward0>)
epoch: 973 loss: tensor(6.8227, grad_fn=<MseLossBackward0>)
epoch: 974 loss: tensor(6.8180, grad_fn=<MseLossBackward0>)
epoch: 975 loss: tensor(6.8132, grad_fn=<MseLossBackward0>)
epoch: 976 loss: tensor(6.8086, grad_fn=

epoch: 1095 loss: tensor(6.1502, grad_fn=<MseLossBackward0>)
epoch: 1096 loss: tensor(6.1439, grad_fn=<MseLossBackward0>)
epoch: 1097 loss: tensor(6.1376, grad_fn=<MseLossBackward0>)
epoch: 1098 loss: tensor(6.1313, grad_fn=<MseLossBackward0>)
epoch: 1099 loss: tensor(6.1250, grad_fn=<MseLossBackward0>)
epoch: 1100 loss: tensor(6.1186, grad_fn=<MseLossBackward0>)
epoch: 1101 loss: tensor(6.1124, grad_fn=<MseLossBackward0>)
epoch: 1102 loss: tensor(6.1061, grad_fn=<MseLossBackward0>)
epoch: 1103 loss: tensor(6.0997, grad_fn=<MseLossBackward0>)
epoch: 1104 loss: tensor(6.0934, grad_fn=<MseLossBackward0>)
epoch: 1105 loss: tensor(6.0869, grad_fn=<MseLossBackward0>)
epoch: 1106 loss: tensor(6.0804, grad_fn=<MseLossBackward0>)
epoch: 1107 loss: tensor(6.0739, grad_fn=<MseLossBackward0>)
epoch: 1108 loss: tensor(6.0673, grad_fn=<MseLossBackward0>)
epoch: 1109 loss: tensor(6.0607, grad_fn=<MseLossBackward0>)
epoch: 1110 loss: tensor(6.0542, grad_fn=<MseLossBackward0>)
epoch: 1111 loss: tensor

epoch: 1230 loss: tensor(5.2365, grad_fn=<MseLossBackward0>)
epoch: 1231 loss: tensor(5.2291, grad_fn=<MseLossBackward0>)
epoch: 1232 loss: tensor(5.2217, grad_fn=<MseLossBackward0>)
epoch: 1233 loss: tensor(5.2143, grad_fn=<MseLossBackward0>)
epoch: 1234 loss: tensor(5.2068, grad_fn=<MseLossBackward0>)
epoch: 1235 loss: tensor(5.1992, grad_fn=<MseLossBackward0>)
epoch: 1236 loss: tensor(5.1917, grad_fn=<MseLossBackward0>)
epoch: 1237 loss: tensor(5.1841, grad_fn=<MseLossBackward0>)
epoch: 1238 loss: tensor(5.1766, grad_fn=<MseLossBackward0>)
epoch: 1239 loss: tensor(5.1690, grad_fn=<MseLossBackward0>)
epoch: 1240 loss: tensor(5.1613, grad_fn=<MseLossBackward0>)
epoch: 1241 loss: tensor(5.1536, grad_fn=<MseLossBackward0>)
epoch: 1242 loss: tensor(5.1458, grad_fn=<MseLossBackward0>)
epoch: 1243 loss: tensor(5.1380, grad_fn=<MseLossBackward0>)
epoch: 1244 loss: tensor(5.1302, grad_fn=<MseLossBackward0>)
epoch: 1245 loss: tensor(5.1223, grad_fn=<MseLossBackward0>)
epoch: 1246 loss: tensor

epoch: 1365 loss: tensor(4.1149, grad_fn=<MseLossBackward0>)
epoch: 1366 loss: tensor(4.1063, grad_fn=<MseLossBackward0>)
epoch: 1367 loss: tensor(4.0975, grad_fn=<MseLossBackward0>)
epoch: 1368 loss: tensor(4.0887, grad_fn=<MseLossBackward0>)
epoch: 1369 loss: tensor(4.0799, grad_fn=<MseLossBackward0>)
epoch: 1370 loss: tensor(4.0711, grad_fn=<MseLossBackward0>)
epoch: 1371 loss: tensor(4.0623, grad_fn=<MseLossBackward0>)
epoch: 1372 loss: tensor(4.0533, grad_fn=<MseLossBackward0>)
epoch: 1373 loss: tensor(4.0444, grad_fn=<MseLossBackward0>)
epoch: 1374 loss: tensor(4.0354, grad_fn=<MseLossBackward0>)
epoch: 1375 loss: tensor(4.0264, grad_fn=<MseLossBackward0>)
epoch: 1376 loss: tensor(4.0175, grad_fn=<MseLossBackward0>)
epoch: 1377 loss: tensor(4.0085, grad_fn=<MseLossBackward0>)
epoch: 1378 loss: tensor(3.9995, grad_fn=<MseLossBackward0>)
epoch: 1379 loss: tensor(3.9904, grad_fn=<MseLossBackward0>)
epoch: 1380 loss: tensor(3.9811, grad_fn=<MseLossBackward0>)
epoch: 1381 loss: tensor

epoch: 1500 loss: tensor(2.8041, grad_fn=<MseLossBackward0>)
epoch: 1501 loss: tensor(2.7952, grad_fn=<MseLossBackward0>)
epoch: 1502 loss: tensor(2.7864, grad_fn=<MseLossBackward0>)
epoch: 1503 loss: tensor(2.7777, grad_fn=<MseLossBackward0>)
epoch: 1504 loss: tensor(2.7690, grad_fn=<MseLossBackward0>)
epoch: 1505 loss: tensor(2.7602, grad_fn=<MseLossBackward0>)
epoch: 1506 loss: tensor(2.7514, grad_fn=<MseLossBackward0>)
epoch: 1507 loss: tensor(2.7428, grad_fn=<MseLossBackward0>)
epoch: 1508 loss: tensor(2.7343, grad_fn=<MseLossBackward0>)
epoch: 1509 loss: tensor(2.7258, grad_fn=<MseLossBackward0>)
epoch: 1510 loss: tensor(2.7173, grad_fn=<MseLossBackward0>)
epoch: 1511 loss: tensor(2.7088, grad_fn=<MseLossBackward0>)
epoch: 1512 loss: tensor(2.7002, grad_fn=<MseLossBackward0>)
epoch: 1513 loss: tensor(2.6917, grad_fn=<MseLossBackward0>)
epoch: 1514 loss: tensor(2.6832, grad_fn=<MseLossBackward0>)
epoch: 1515 loss: tensor(2.6746, grad_fn=<MseLossBackward0>)
epoch: 1516 loss: tensor

epoch: 1635 loss: tensor(1.6575, grad_fn=<MseLossBackward0>)
epoch: 1636 loss: tensor(1.6490, grad_fn=<MseLossBackward0>)
epoch: 1637 loss: tensor(1.6407, grad_fn=<MseLossBackward0>)
epoch: 1638 loss: tensor(1.6324, grad_fn=<MseLossBackward0>)
epoch: 1639 loss: tensor(1.6243, grad_fn=<MseLossBackward0>)
epoch: 1640 loss: tensor(1.6162, grad_fn=<MseLossBackward0>)
epoch: 1641 loss: tensor(1.6082, grad_fn=<MseLossBackward0>)
epoch: 1642 loss: tensor(1.6001, grad_fn=<MseLossBackward0>)
epoch: 1643 loss: tensor(1.5920, grad_fn=<MseLossBackward0>)
epoch: 1644 loss: tensor(1.5839, grad_fn=<MseLossBackward0>)
epoch: 1645 loss: tensor(1.5757, grad_fn=<MseLossBackward0>)
epoch: 1646 loss: tensor(1.5676, grad_fn=<MseLossBackward0>)
epoch: 1647 loss: tensor(1.5595, grad_fn=<MseLossBackward0>)
epoch: 1648 loss: tensor(1.5515, grad_fn=<MseLossBackward0>)
epoch: 1649 loss: tensor(1.5435, grad_fn=<MseLossBackward0>)
epoch: 1650 loss: tensor(1.5355, grad_fn=<MseLossBackward0>)
epoch: 1651 loss: tensor

epoch: 1770 loss: tensor(0.7791, grad_fn=<MseLossBackward0>)
epoch: 1771 loss: tensor(0.7746, grad_fn=<MseLossBackward0>)
epoch: 1772 loss: tensor(0.7697, grad_fn=<MseLossBackward0>)
epoch: 1773 loss: tensor(0.7651, grad_fn=<MseLossBackward0>)
epoch: 1774 loss: tensor(0.7610, grad_fn=<MseLossBackward0>)
epoch: 1775 loss: tensor(0.7569, grad_fn=<MseLossBackward0>)
epoch: 1776 loss: tensor(0.7526, grad_fn=<MseLossBackward0>)
epoch: 1777 loss: tensor(0.7479, grad_fn=<MseLossBackward0>)
epoch: 1778 loss: tensor(0.7432, grad_fn=<MseLossBackward0>)
epoch: 1779 loss: tensor(0.7387, grad_fn=<MseLossBackward0>)
epoch: 1780 loss: tensor(0.7344, grad_fn=<MseLossBackward0>)
epoch: 1781 loss: tensor(0.7299, grad_fn=<MseLossBackward0>)
epoch: 1782 loss: tensor(0.7253, grad_fn=<MseLossBackward0>)
epoch: 1783 loss: tensor(0.7207, grad_fn=<MseLossBackward0>)
epoch: 1784 loss: tensor(0.7162, grad_fn=<MseLossBackward0>)
epoch: 1785 loss: tensor(0.7119, grad_fn=<MseLossBackward0>)
epoch: 1786 loss: tensor

epoch: 1905 loss: tensor(0.3459, grad_fn=<MseLossBackward0>)
epoch: 1906 loss: tensor(0.3439, grad_fn=<MseLossBackward0>)
epoch: 1907 loss: tensor(0.3419, grad_fn=<MseLossBackward0>)
epoch: 1908 loss: tensor(0.3399, grad_fn=<MseLossBackward0>)
epoch: 1909 loss: tensor(0.3379, grad_fn=<MseLossBackward0>)
epoch: 1910 loss: tensor(0.3359, grad_fn=<MseLossBackward0>)
epoch: 1911 loss: tensor(0.3339, grad_fn=<MseLossBackward0>)
epoch: 1912 loss: tensor(0.3320, grad_fn=<MseLossBackward0>)
epoch: 1913 loss: tensor(0.3300, grad_fn=<MseLossBackward0>)
epoch: 1914 loss: tensor(0.3281, grad_fn=<MseLossBackward0>)
epoch: 1915 loss: tensor(0.3261, grad_fn=<MseLossBackward0>)
epoch: 1916 loss: tensor(0.3242, grad_fn=<MseLossBackward0>)
epoch: 1917 loss: tensor(0.3222, grad_fn=<MseLossBackward0>)
epoch: 1918 loss: tensor(0.3203, grad_fn=<MseLossBackward0>)
epoch: 1919 loss: tensor(0.3183, grad_fn=<MseLossBackward0>)
epoch: 1920 loss: tensor(0.3164, grad_fn=<MseLossBackward0>)
epoch: 1921 loss: tensor

epoch: 2040 loss: tensor(0.1673, grad_fn=<MseLossBackward0>)
epoch: 2041 loss: tensor(0.1664, grad_fn=<MseLossBackward0>)
epoch: 2042 loss: tensor(0.1656, grad_fn=<MseLossBackward0>)
epoch: 2043 loss: tensor(0.1649, grad_fn=<MseLossBackward0>)
epoch: 2044 loss: tensor(0.1641, grad_fn=<MseLossBackward0>)
epoch: 2045 loss: tensor(0.1633, grad_fn=<MseLossBackward0>)
epoch: 2046 loss: tensor(0.1625, grad_fn=<MseLossBackward0>)
epoch: 2047 loss: tensor(0.1617, grad_fn=<MseLossBackward0>)
epoch: 2048 loss: tensor(0.1609, grad_fn=<MseLossBackward0>)
epoch: 2049 loss: tensor(0.1601, grad_fn=<MseLossBackward0>)
epoch: 2050 loss: tensor(0.1593, grad_fn=<MseLossBackward0>)
epoch: 2051 loss: tensor(0.1585, grad_fn=<MseLossBackward0>)
epoch: 2052 loss: tensor(0.1577, grad_fn=<MseLossBackward0>)
epoch: 2053 loss: tensor(0.1569, grad_fn=<MseLossBackward0>)
epoch: 2054 loss: tensor(0.1561, grad_fn=<MseLossBackward0>)
epoch: 2055 loss: tensor(0.1553, grad_fn=<MseLossBackward0>)
epoch: 2056 loss: tensor

epoch: 2175 loss: tensor(0.0940, grad_fn=<MseLossBackward0>)
epoch: 2176 loss: tensor(0.0937, grad_fn=<MseLossBackward0>)
epoch: 2177 loss: tensor(0.0934, grad_fn=<MseLossBackward0>)
epoch: 2178 loss: tensor(0.0931, grad_fn=<MseLossBackward0>)
epoch: 2179 loss: tensor(0.0927, grad_fn=<MseLossBackward0>)
epoch: 2180 loss: tensor(0.0924, grad_fn=<MseLossBackward0>)
epoch: 2181 loss: tensor(0.0921, grad_fn=<MseLossBackward0>)
epoch: 2182 loss: tensor(0.0918, grad_fn=<MseLossBackward0>)
epoch: 2183 loss: tensor(0.0915, grad_fn=<MseLossBackward0>)
epoch: 2184 loss: tensor(0.0912, grad_fn=<MseLossBackward0>)
epoch: 2185 loss: tensor(0.0908, grad_fn=<MseLossBackward0>)
epoch: 2186 loss: tensor(0.0905, grad_fn=<MseLossBackward0>)
epoch: 2187 loss: tensor(0.0902, grad_fn=<MseLossBackward0>)
epoch: 2188 loss: tensor(0.0899, grad_fn=<MseLossBackward0>)
epoch: 2189 loss: tensor(0.0896, grad_fn=<MseLossBackward0>)
epoch: 2190 loss: tensor(0.0893, grad_fn=<MseLossBackward0>)
epoch: 2191 loss: tensor

epoch: 2310 loss: tensor(0.0620, grad_fn=<MseLossBackward0>)
epoch: 2311 loss: tensor(0.0618, grad_fn=<MseLossBackward0>)
epoch: 2312 loss: tensor(0.0616, grad_fn=<MseLossBackward0>)
epoch: 2313 loss: tensor(0.0614, grad_fn=<MseLossBackward0>)
epoch: 2314 loss: tensor(0.0613, grad_fn=<MseLossBackward0>)
epoch: 2315 loss: tensor(0.0611, grad_fn=<MseLossBackward0>)
epoch: 2316 loss: tensor(0.0609, grad_fn=<MseLossBackward0>)
epoch: 2317 loss: tensor(0.0607, grad_fn=<MseLossBackward0>)
epoch: 2318 loss: tensor(0.0605, grad_fn=<MseLossBackward0>)
epoch: 2319 loss: tensor(0.0604, grad_fn=<MseLossBackward0>)
epoch: 2320 loss: tensor(0.0602, grad_fn=<MseLossBackward0>)
epoch: 2321 loss: tensor(0.0600, grad_fn=<MseLossBackward0>)
epoch: 2322 loss: tensor(0.0599, grad_fn=<MseLossBackward0>)
epoch: 2323 loss: tensor(0.0597, grad_fn=<MseLossBackward0>)
epoch: 2324 loss: tensor(0.0595, grad_fn=<MseLossBackward0>)
epoch: 2325 loss: tensor(0.0594, grad_fn=<MseLossBackward0>)
epoch: 2326 loss: tensor

epoch: 2445 loss: tensor(0.0432, grad_fn=<MseLossBackward0>)
epoch: 2446 loss: tensor(0.0431, grad_fn=<MseLossBackward0>)
epoch: 2447 loss: tensor(0.0430, grad_fn=<MseLossBackward0>)
epoch: 2448 loss: tensor(0.0429, grad_fn=<MseLossBackward0>)
epoch: 2449 loss: tensor(0.0427, grad_fn=<MseLossBackward0>)
epoch: 2450 loss: tensor(0.0426, grad_fn=<MseLossBackward0>)
epoch: 2451 loss: tensor(0.0425, grad_fn=<MseLossBackward0>)
epoch: 2452 loss: tensor(0.0424, grad_fn=<MseLossBackward0>)
epoch: 2453 loss: tensor(0.0423, grad_fn=<MseLossBackward0>)
epoch: 2454 loss: tensor(0.0422, grad_fn=<MseLossBackward0>)
epoch: 2455 loss: tensor(0.0421, grad_fn=<MseLossBackward0>)
epoch: 2456 loss: tensor(0.0420, grad_fn=<MseLossBackward0>)
epoch: 2457 loss: tensor(0.0419, grad_fn=<MseLossBackward0>)
epoch: 2458 loss: tensor(0.0418, grad_fn=<MseLossBackward0>)
epoch: 2459 loss: tensor(0.0417, grad_fn=<MseLossBackward0>)
epoch: 2460 loss: tensor(0.0416, grad_fn=<MseLossBackward0>)
epoch: 2461 loss: tensor

epoch: 2580 loss: tensor(0.0313, grad_fn=<MseLossBackward0>)
epoch: 2581 loss: tensor(0.0312, grad_fn=<MseLossBackward0>)
epoch: 2582 loss: tensor(0.0311, grad_fn=<MseLossBackward0>)
epoch: 2583 loss: tensor(0.0311, grad_fn=<MseLossBackward0>)
epoch: 2584 loss: tensor(0.0310, grad_fn=<MseLossBackward0>)
epoch: 2585 loss: tensor(0.0309, grad_fn=<MseLossBackward0>)
epoch: 2586 loss: tensor(0.0309, grad_fn=<MseLossBackward0>)
epoch: 2587 loss: tensor(0.0308, grad_fn=<MseLossBackward0>)
epoch: 2588 loss: tensor(0.0307, grad_fn=<MseLossBackward0>)
epoch: 2589 loss: tensor(0.0307, grad_fn=<MseLossBackward0>)
epoch: 2590 loss: tensor(0.0306, grad_fn=<MseLossBackward0>)
epoch: 2591 loss: tensor(0.0305, grad_fn=<MseLossBackward0>)
epoch: 2592 loss: tensor(0.0304, grad_fn=<MseLossBackward0>)
epoch: 2593 loss: tensor(0.0304, grad_fn=<MseLossBackward0>)
epoch: 2594 loss: tensor(0.0303, grad_fn=<MseLossBackward0>)
epoch: 2595 loss: tensor(0.0302, grad_fn=<MseLossBackward0>)
epoch: 2596 loss: tensor

epoch: 2715 loss: tensor(0.0232, grad_fn=<MseLossBackward0>)
epoch: 2716 loss: tensor(0.0231, grad_fn=<MseLossBackward0>)
epoch: 2717 loss: tensor(0.0231, grad_fn=<MseLossBackward0>)
epoch: 2718 loss: tensor(0.0230, grad_fn=<MseLossBackward0>)
epoch: 2719 loss: tensor(0.0230, grad_fn=<MseLossBackward0>)
epoch: 2720 loss: tensor(0.0229, grad_fn=<MseLossBackward0>)
epoch: 2721 loss: tensor(0.0229, grad_fn=<MseLossBackward0>)
epoch: 2722 loss: tensor(0.0228, grad_fn=<MseLossBackward0>)
epoch: 2723 loss: tensor(0.0228, grad_fn=<MseLossBackward0>)
epoch: 2724 loss: tensor(0.0227, grad_fn=<MseLossBackward0>)
epoch: 2725 loss: tensor(0.0227, grad_fn=<MseLossBackward0>)
epoch: 2726 loss: tensor(0.0227, grad_fn=<MseLossBackward0>)
epoch: 2727 loss: tensor(0.0226, grad_fn=<MseLossBackward0>)
epoch: 2728 loss: tensor(0.0226, grad_fn=<MseLossBackward0>)
epoch: 2729 loss: tensor(0.0225, grad_fn=<MseLossBackward0>)
epoch: 2730 loss: tensor(0.0225, grad_fn=<MseLossBackward0>)
epoch: 2731 loss: tensor

epoch: 2850 loss: tensor(0.0183, grad_fn=<MseLossBackward0>)
epoch: 2851 loss: tensor(0.0182, grad_fn=<MseLossBackward0>)
epoch: 2852 loss: tensor(0.0178, grad_fn=<MseLossBackward0>)
epoch: 2853 loss: tensor(0.0176, grad_fn=<MseLossBackward0>)
epoch: 2854 loss: tensor(0.0176, grad_fn=<MseLossBackward0>)
epoch: 2855 loss: tensor(0.0178, grad_fn=<MseLossBackward0>)
epoch: 2856 loss: tensor(0.0178, grad_fn=<MseLossBackward0>)
epoch: 2857 loss: tensor(0.0177, grad_fn=<MseLossBackward0>)
epoch: 2858 loss: tensor(0.0175, grad_fn=<MseLossBackward0>)
epoch: 2859 loss: tensor(0.0174, grad_fn=<MseLossBackward0>)
epoch: 2860 loss: tensor(0.0174, grad_fn=<MseLossBackward0>)
epoch: 2861 loss: tensor(0.0175, grad_fn=<MseLossBackward0>)
epoch: 2862 loss: tensor(0.0175, grad_fn=<MseLossBackward0>)
epoch: 2863 loss: tensor(0.0174, grad_fn=<MseLossBackward0>)
epoch: 2864 loss: tensor(0.0172, grad_fn=<MseLossBackward0>)
epoch: 2865 loss: tensor(0.0172, grad_fn=<MseLossBackward0>)
epoch: 2866 loss: tensor

epoch: 2985 loss: tensor(0.0137, grad_fn=<MseLossBackward0>)
epoch: 2986 loss: tensor(0.0137, grad_fn=<MseLossBackward0>)
epoch: 2987 loss: tensor(0.0137, grad_fn=<MseLossBackward0>)
epoch: 2988 loss: tensor(0.0137, grad_fn=<MseLossBackward0>)
epoch: 2989 loss: tensor(0.0136, grad_fn=<MseLossBackward0>)
epoch: 2990 loss: tensor(0.0136, grad_fn=<MseLossBackward0>)
epoch: 2991 loss: tensor(0.0136, grad_fn=<MseLossBackward0>)
epoch: 2992 loss: tensor(0.0136, grad_fn=<MseLossBackward0>)
epoch: 2993 loss: tensor(0.0135, grad_fn=<MseLossBackward0>)
epoch: 2994 loss: tensor(0.0135, grad_fn=<MseLossBackward0>)
epoch: 2995 loss: tensor(0.0135, grad_fn=<MseLossBackward0>)
epoch: 2996 loss: tensor(0.0135, grad_fn=<MseLossBackward0>)
epoch: 2997 loss: tensor(0.0134, grad_fn=<MseLossBackward0>)
epoch: 2998 loss: tensor(0.0134, grad_fn=<MseLossBackward0>)
epoch: 2999 loss: tensor(0.0134, grad_fn=<MseLossBackward0>)
epoch: 3000 loss: tensor(0.0134, grad_fn=<MseLossBackward0>)
epoch: 3001 loss: tensor

epoch: 3120 loss: tensor(0.0107, grad_fn=<MseLossBackward0>)
epoch: 3121 loss: tensor(0.0107, grad_fn=<MseLossBackward0>)
epoch: 3122 loss: tensor(0.0107, grad_fn=<MseLossBackward0>)
epoch: 3123 loss: tensor(0.0107, grad_fn=<MseLossBackward0>)
epoch: 3124 loss: tensor(0.0106, grad_fn=<MseLossBackward0>)
epoch: 3125 loss: tensor(0.0106, grad_fn=<MseLossBackward0>)
epoch: 3126 loss: tensor(0.0106, grad_fn=<MseLossBackward0>)
epoch: 3127 loss: tensor(0.0106, grad_fn=<MseLossBackward0>)
epoch: 3128 loss: tensor(0.0106, grad_fn=<MseLossBackward0>)
epoch: 3129 loss: tensor(0.0105, grad_fn=<MseLossBackward0>)
epoch: 3130 loss: tensor(0.0105, grad_fn=<MseLossBackward0>)
epoch: 3131 loss: tensor(0.0105, grad_fn=<MseLossBackward0>)
epoch: 3132 loss: tensor(0.0105, grad_fn=<MseLossBackward0>)
epoch: 3133 loss: tensor(0.0105, grad_fn=<MseLossBackward0>)
epoch: 3134 loss: tensor(0.0105, grad_fn=<MseLossBackward0>)
epoch: 3135 loss: tensor(0.0104, grad_fn=<MseLossBackward0>)
epoch: 3136 loss: tensor

epoch: 3255 loss: tensor(0.0086, grad_fn=<MseLossBackward0>)
epoch: 3256 loss: tensor(0.0086, grad_fn=<MseLossBackward0>)
epoch: 3257 loss: tensor(0.0085, grad_fn=<MseLossBackward0>)
epoch: 3258 loss: tensor(0.0085, grad_fn=<MseLossBackward0>)
epoch: 3259 loss: tensor(0.0085, grad_fn=<MseLossBackward0>)
epoch: 3260 loss: tensor(0.0085, grad_fn=<MseLossBackward0>)
epoch: 3261 loss: tensor(0.0085, grad_fn=<MseLossBackward0>)
epoch: 3262 loss: tensor(0.0085, grad_fn=<MseLossBackward0>)
epoch: 3263 loss: tensor(0.0085, grad_fn=<MseLossBackward0>)
epoch: 3264 loss: tensor(0.0085, grad_fn=<MseLossBackward0>)
epoch: 3265 loss: tensor(0.0084, grad_fn=<MseLossBackward0>)
epoch: 3266 loss: tensor(0.0084, grad_fn=<MseLossBackward0>)
epoch: 3267 loss: tensor(0.0084, grad_fn=<MseLossBackward0>)
epoch: 3268 loss: tensor(0.0084, grad_fn=<MseLossBackward0>)
epoch: 3269 loss: tensor(0.0084, grad_fn=<MseLossBackward0>)
epoch: 3270 loss: tensor(0.0084, grad_fn=<MseLossBackward0>)
epoch: 3271 loss: tensor

epoch: 3390 loss: tensor(0.0070, grad_fn=<MseLossBackward0>)
epoch: 3391 loss: tensor(0.0069, grad_fn=<MseLossBackward0>)
epoch: 3392 loss: tensor(0.0069, grad_fn=<MseLossBackward0>)
epoch: 3393 loss: tensor(0.0069, grad_fn=<MseLossBackward0>)
epoch: 3394 loss: tensor(0.0069, grad_fn=<MseLossBackward0>)
epoch: 3395 loss: tensor(0.0069, grad_fn=<MseLossBackward0>)
epoch: 3396 loss: tensor(0.0069, grad_fn=<MseLossBackward0>)
epoch: 3397 loss: tensor(0.0069, grad_fn=<MseLossBackward0>)
epoch: 3398 loss: tensor(0.0069, grad_fn=<MseLossBackward0>)
epoch: 3399 loss: tensor(0.0069, grad_fn=<MseLossBackward0>)
epoch: 3400 loss: tensor(0.0068, grad_fn=<MseLossBackward0>)
epoch: 3401 loss: tensor(0.0068, grad_fn=<MseLossBackward0>)
epoch: 3402 loss: tensor(0.0068, grad_fn=<MseLossBackward0>)
epoch: 3403 loss: tensor(0.0068, grad_fn=<MseLossBackward0>)
epoch: 3404 loss: tensor(0.0068, grad_fn=<MseLossBackward0>)
epoch: 3405 loss: tensor(0.0068, grad_fn=<MseLossBackward0>)
epoch: 3406 loss: tensor

epoch: 3525 loss: tensor(0.0057, grad_fn=<MseLossBackward0>)
epoch: 3526 loss: tensor(0.0058, grad_fn=<MseLossBackward0>)
epoch: 3527 loss: tensor(0.0058, grad_fn=<MseLossBackward0>)
epoch: 3528 loss: tensor(0.0057, grad_fn=<MseLossBackward0>)
epoch: 3529 loss: tensor(0.0057, grad_fn=<MseLossBackward0>)
epoch: 3530 loss: tensor(0.0056, grad_fn=<MseLossBackward0>)
epoch: 3531 loss: tensor(0.0056, grad_fn=<MseLossBackward0>)
epoch: 3532 loss: tensor(0.0056, grad_fn=<MseLossBackward0>)
epoch: 3533 loss: tensor(0.0056, grad_fn=<MseLossBackward0>)
epoch: 3534 loss: tensor(0.0057, grad_fn=<MseLossBackward0>)
epoch: 3535 loss: tensor(0.0056, grad_fn=<MseLossBackward0>)
epoch: 3536 loss: tensor(0.0056, grad_fn=<MseLossBackward0>)
epoch: 3537 loss: tensor(0.0056, grad_fn=<MseLossBackward0>)
epoch: 3538 loss: tensor(0.0056, grad_fn=<MseLossBackward0>)
epoch: 3539 loss: tensor(0.0055, grad_fn=<MseLossBackward0>)
epoch: 3540 loss: tensor(0.0056, grad_fn=<MseLossBackward0>)
epoch: 3541 loss: tensor

epoch: 3660 loss: tensor(0.0069, grad_fn=<MseLossBackward0>)
epoch: 3661 loss: tensor(0.0081, grad_fn=<MseLossBackward0>)
epoch: 3662 loss: tensor(0.0097, grad_fn=<MseLossBackward0>)
epoch: 3663 loss: tensor(0.0116, grad_fn=<MseLossBackward0>)
epoch: 3664 loss: tensor(0.0134, grad_fn=<MseLossBackward0>)
epoch: 3665 loss: tensor(0.0143, grad_fn=<MseLossBackward0>)
epoch: 3666 loss: tensor(0.0133, grad_fn=<MseLossBackward0>)
epoch: 3667 loss: tensor(0.0103, grad_fn=<MseLossBackward0>)
epoch: 3668 loss: tensor(0.0068, grad_fn=<MseLossBackward0>)
epoch: 3669 loss: tensor(0.0048, grad_fn=<MseLossBackward0>)
epoch: 3670 loss: tensor(0.0049, grad_fn=<MseLossBackward0>)
epoch: 3671 loss: tensor(0.0066, grad_fn=<MseLossBackward0>)
epoch: 3672 loss: tensor(0.0082, grad_fn=<MseLossBackward0>)
epoch: 3673 loss: tensor(0.0084, grad_fn=<MseLossBackward0>)
epoch: 3674 loss: tensor(0.0070, grad_fn=<MseLossBackward0>)
epoch: 3675 loss: tensor(0.0053, grad_fn=<MseLossBackward0>)
epoch: 3676 loss: tensor

epoch: 3795 loss: tensor(0.0039, grad_fn=<MseLossBackward0>)
epoch: 3796 loss: tensor(0.0038, grad_fn=<MseLossBackward0>)
epoch: 3797 loss: tensor(0.0038, grad_fn=<MseLossBackward0>)
epoch: 3798 loss: tensor(0.0038, grad_fn=<MseLossBackward0>)
epoch: 3799 loss: tensor(0.0038, grad_fn=<MseLossBackward0>)
epoch: 3800 loss: tensor(0.0038, grad_fn=<MseLossBackward0>)
epoch: 3801 loss: tensor(0.0038, grad_fn=<MseLossBackward0>)
epoch: 3802 loss: tensor(0.0038, grad_fn=<MseLossBackward0>)
epoch: 3803 loss: tensor(0.0038, grad_fn=<MseLossBackward0>)
epoch: 3804 loss: tensor(0.0038, grad_fn=<MseLossBackward0>)
epoch: 3805 loss: tensor(0.0038, grad_fn=<MseLossBackward0>)
epoch: 3806 loss: tensor(0.0038, grad_fn=<MseLossBackward0>)
epoch: 3807 loss: tensor(0.0038, grad_fn=<MseLossBackward0>)
epoch: 3808 loss: tensor(0.0038, grad_fn=<MseLossBackward0>)
epoch: 3809 loss: tensor(0.0038, grad_fn=<MseLossBackward0>)
epoch: 3810 loss: tensor(0.0038, grad_fn=<MseLossBackward0>)
epoch: 3811 loss: tensor

epoch: 3930 loss: tensor(0.0033, grad_fn=<MseLossBackward0>)
epoch: 3931 loss: tensor(0.0033, grad_fn=<MseLossBackward0>)
epoch: 3932 loss: tensor(0.0033, grad_fn=<MseLossBackward0>)
epoch: 3933 loss: tensor(0.0033, grad_fn=<MseLossBackward0>)
epoch: 3934 loss: tensor(0.0033, grad_fn=<MseLossBackward0>)
epoch: 3935 loss: tensor(0.0033, grad_fn=<MseLossBackward0>)
epoch: 3936 loss: tensor(0.0033, grad_fn=<MseLossBackward0>)
epoch: 3937 loss: tensor(0.0033, grad_fn=<MseLossBackward0>)
epoch: 3938 loss: tensor(0.0033, grad_fn=<MseLossBackward0>)
epoch: 3939 loss: tensor(0.0033, grad_fn=<MseLossBackward0>)
epoch: 3940 loss: tensor(0.0033, grad_fn=<MseLossBackward0>)
epoch: 3941 loss: tensor(0.0033, grad_fn=<MseLossBackward0>)
epoch: 3942 loss: tensor(0.0033, grad_fn=<MseLossBackward0>)
epoch: 3943 loss: tensor(0.0033, grad_fn=<MseLossBackward0>)
epoch: 3944 loss: tensor(0.0032, grad_fn=<MseLossBackward0>)
epoch: 3945 loss: tensor(0.0032, grad_fn=<MseLossBackward0>)
epoch: 3946 loss: tensor

epoch: 4065 loss: tensor(0.0031, grad_fn=<MseLossBackward0>)
epoch: 4066 loss: tensor(0.0029, grad_fn=<MseLossBackward0>)
epoch: 4067 loss: tensor(0.0028, grad_fn=<MseLossBackward0>)
epoch: 4068 loss: tensor(0.0028, grad_fn=<MseLossBackward0>)
epoch: 4069 loss: tensor(0.0028, grad_fn=<MseLossBackward0>)
epoch: 4070 loss: tensor(0.0029, grad_fn=<MseLossBackward0>)
epoch: 4071 loss: tensor(0.0029, grad_fn=<MseLossBackward0>)
epoch: 4072 loss: tensor(0.0029, grad_fn=<MseLossBackward0>)
epoch: 4073 loss: tensor(0.0029, grad_fn=<MseLossBackward0>)
epoch: 4074 loss: tensor(0.0028, grad_fn=<MseLossBackward0>)
epoch: 4075 loss: tensor(0.0028, grad_fn=<MseLossBackward0>)
epoch: 4076 loss: tensor(0.0028, grad_fn=<MseLossBackward0>)
epoch: 4077 loss: tensor(0.0028, grad_fn=<MseLossBackward0>)
epoch: 4078 loss: tensor(0.0028, grad_fn=<MseLossBackward0>)
epoch: 4079 loss: tensor(0.0028, grad_fn=<MseLossBackward0>)
epoch: 4080 loss: tensor(0.0028, grad_fn=<MseLossBackward0>)
epoch: 4081 loss: tensor

epoch: 4200 loss: tensor(0.0081, grad_fn=<MseLossBackward0>)
epoch: 4201 loss: tensor(0.0094, grad_fn=<MseLossBackward0>)
epoch: 4202 loss: tensor(0.0102, grad_fn=<MseLossBackward0>)
epoch: 4203 loss: tensor(0.0100, grad_fn=<MseLossBackward0>)
epoch: 4204 loss: tensor(0.0084, grad_fn=<MseLossBackward0>)
epoch: 4205 loss: tensor(0.0059, grad_fn=<MseLossBackward0>)
epoch: 4206 loss: tensor(0.0036, grad_fn=<MseLossBackward0>)
epoch: 4207 loss: tensor(0.0025, grad_fn=<MseLossBackward0>)
epoch: 4208 loss: tensor(0.0027, grad_fn=<MseLossBackward0>)
epoch: 4209 loss: tensor(0.0039, grad_fn=<MseLossBackward0>)
epoch: 4210 loss: tensor(0.0050, grad_fn=<MseLossBackward0>)
epoch: 4211 loss: tensor(0.0054, grad_fn=<MseLossBackward0>)
epoch: 4212 loss: tensor(0.0048, grad_fn=<MseLossBackward0>)
epoch: 4213 loss: tensor(0.0036, grad_fn=<MseLossBackward0>)
epoch: 4214 loss: tensor(0.0027, grad_fn=<MseLossBackward0>)
epoch: 4215 loss: tensor(0.0024, grad_fn=<MseLossBackward0>)
epoch: 4216 loss: tensor

epoch: 4335 loss: tensor(0.0022, grad_fn=<MseLossBackward0>)
epoch: 4336 loss: tensor(0.0022, grad_fn=<MseLossBackward0>)
epoch: 4337 loss: tensor(0.0022, grad_fn=<MseLossBackward0>)
epoch: 4338 loss: tensor(0.0022, grad_fn=<MseLossBackward0>)
epoch: 4339 loss: tensor(0.0022, grad_fn=<MseLossBackward0>)
epoch: 4340 loss: tensor(0.0022, grad_fn=<MseLossBackward0>)
epoch: 4341 loss: tensor(0.0022, grad_fn=<MseLossBackward0>)
epoch: 4342 loss: tensor(0.0022, grad_fn=<MseLossBackward0>)
epoch: 4343 loss: tensor(0.0022, grad_fn=<MseLossBackward0>)
epoch: 4344 loss: tensor(0.0022, grad_fn=<MseLossBackward0>)
epoch: 4345 loss: tensor(0.0022, grad_fn=<MseLossBackward0>)
epoch: 4346 loss: tensor(0.0022, grad_fn=<MseLossBackward0>)
epoch: 4347 loss: tensor(0.0022, grad_fn=<MseLossBackward0>)
epoch: 4348 loss: tensor(0.0022, grad_fn=<MseLossBackward0>)
epoch: 4349 loss: tensor(0.0022, grad_fn=<MseLossBackward0>)
epoch: 4350 loss: tensor(0.0022, grad_fn=<MseLossBackward0>)
epoch: 4351 loss: tensor

epoch: 4470 loss: tensor(0.0020, grad_fn=<MseLossBackward0>)
epoch: 4471 loss: tensor(0.0020, grad_fn=<MseLossBackward0>)
epoch: 4472 loss: tensor(0.0020, grad_fn=<MseLossBackward0>)
epoch: 4473 loss: tensor(0.0020, grad_fn=<MseLossBackward0>)
epoch: 4474 loss: tensor(0.0020, grad_fn=<MseLossBackward0>)
epoch: 4475 loss: tensor(0.0020, grad_fn=<MseLossBackward0>)
epoch: 4476 loss: tensor(0.0020, grad_fn=<MseLossBackward0>)
epoch: 4477 loss: tensor(0.0020, grad_fn=<MseLossBackward0>)
epoch: 4478 loss: tensor(0.0020, grad_fn=<MseLossBackward0>)
epoch: 4479 loss: tensor(0.0021, grad_fn=<MseLossBackward0>)
epoch: 4480 loss: tensor(0.0021, grad_fn=<MseLossBackward0>)
epoch: 4481 loss: tensor(0.0022, grad_fn=<MseLossBackward0>)
epoch: 4482 loss: tensor(0.0022, grad_fn=<MseLossBackward0>)
epoch: 4483 loss: tensor(0.0022, grad_fn=<MseLossBackward0>)
epoch: 4484 loss: tensor(0.0022, grad_fn=<MseLossBackward0>)
epoch: 4485 loss: tensor(0.0021, grad_fn=<MseLossBackward0>)
epoch: 4486 loss: tensor

epoch: 4605 loss: tensor(0.0018, grad_fn=<MseLossBackward0>)
epoch: 4606 loss: tensor(0.0018, grad_fn=<MseLossBackward0>)
epoch: 4607 loss: tensor(0.0018, grad_fn=<MseLossBackward0>)
epoch: 4608 loss: tensor(0.0018, grad_fn=<MseLossBackward0>)
epoch: 4609 loss: tensor(0.0018, grad_fn=<MseLossBackward0>)
epoch: 4610 loss: tensor(0.0018, grad_fn=<MseLossBackward0>)
epoch: 4611 loss: tensor(0.0018, grad_fn=<MseLossBackward0>)
epoch: 4612 loss: tensor(0.0018, grad_fn=<MseLossBackward0>)
epoch: 4613 loss: tensor(0.0018, grad_fn=<MseLossBackward0>)
epoch: 4614 loss: tensor(0.0018, grad_fn=<MseLossBackward0>)
epoch: 4615 loss: tensor(0.0017, grad_fn=<MseLossBackward0>)
epoch: 4616 loss: tensor(0.0017, grad_fn=<MseLossBackward0>)
epoch: 4617 loss: tensor(0.0017, grad_fn=<MseLossBackward0>)
epoch: 4618 loss: tensor(0.0017, grad_fn=<MseLossBackward0>)
epoch: 4619 loss: tensor(0.0017, grad_fn=<MseLossBackward0>)
epoch: 4620 loss: tensor(0.0017, grad_fn=<MseLossBackward0>)
epoch: 4621 loss: tensor

epoch: 4740 loss: tensor(0.0027, grad_fn=<MseLossBackward0>)
epoch: 4741 loss: tensor(0.0033, grad_fn=<MseLossBackward0>)
epoch: 4742 loss: tensor(0.0033, grad_fn=<MseLossBackward0>)
epoch: 4743 loss: tensor(0.0026, grad_fn=<MseLossBackward0>)
epoch: 4744 loss: tensor(0.0019, grad_fn=<MseLossBackward0>)
epoch: 4745 loss: tensor(0.0016, grad_fn=<MseLossBackward0>)
epoch: 4746 loss: tensor(0.0018, grad_fn=<MseLossBackward0>)
epoch: 4747 loss: tensor(0.0022, grad_fn=<MseLossBackward0>)
epoch: 4748 loss: tensor(0.0024, grad_fn=<MseLossBackward0>)
epoch: 4749 loss: tensor(0.0024, grad_fn=<MseLossBackward0>)
epoch: 4750 loss: tensor(0.0020, grad_fn=<MseLossBackward0>)
epoch: 4751 loss: tensor(0.0017, grad_fn=<MseLossBackward0>)
epoch: 4752 loss: tensor(0.0016, grad_fn=<MseLossBackward0>)
epoch: 4753 loss: tensor(0.0017, grad_fn=<MseLossBackward0>)
epoch: 4754 loss: tensor(0.0019, grad_fn=<MseLossBackward0>)
epoch: 4755 loss: tensor(0.0020, grad_fn=<MseLossBackward0>)
epoch: 4756 loss: tensor

epoch: 4875 loss: tensor(0.0014, grad_fn=<MseLossBackward0>)
epoch: 4876 loss: tensor(0.0014, grad_fn=<MseLossBackward0>)
epoch: 4877 loss: tensor(0.0014, grad_fn=<MseLossBackward0>)
epoch: 4878 loss: tensor(0.0014, grad_fn=<MseLossBackward0>)
epoch: 4879 loss: tensor(0.0014, grad_fn=<MseLossBackward0>)
epoch: 4880 loss: tensor(0.0014, grad_fn=<MseLossBackward0>)
epoch: 4881 loss: tensor(0.0014, grad_fn=<MseLossBackward0>)
epoch: 4882 loss: tensor(0.0014, grad_fn=<MseLossBackward0>)
epoch: 4883 loss: tensor(0.0014, grad_fn=<MseLossBackward0>)
epoch: 4884 loss: tensor(0.0014, grad_fn=<MseLossBackward0>)
epoch: 4885 loss: tensor(0.0014, grad_fn=<MseLossBackward0>)
epoch: 4886 loss: tensor(0.0014, grad_fn=<MseLossBackward0>)
epoch: 4887 loss: tensor(0.0014, grad_fn=<MseLossBackward0>)
epoch: 4888 loss: tensor(0.0014, grad_fn=<MseLossBackward0>)
epoch: 4889 loss: tensor(0.0014, grad_fn=<MseLossBackward0>)
epoch: 4890 loss: tensor(0.0014, grad_fn=<MseLossBackward0>)
epoch: 4891 loss: tensor

In [26]:
#net = net.to(device)
N_epochs = 10000

labels_temp = np.array(labels_temp)
#train_data_torch = torch.from_numpy(features_temp).float()
#train_target_torch = torch.from_numpy(labels_temp).float()
train_target_torch = torch.tensor(torch.from_numpy(np.array(labels_temp)).float())

import sys
np.set_printoptions(threshold=sys.maxsize)

def validate(net, test_data, test_target, i):
    
    test_data_torch = torch.from_numpy(features_test).float()
    #test_target_torch = torch.from_numpy(labels_test).float()
    test_target_torch = torch.tensor(torch.from_numpy(np.array(test_target)).float())

    test_pred = np.rint(net(test_data_torch).detach().numpy())
    if i % 500 == 0:
        print(np.concatenate((test_pred, test_target_torch.detach().numpy()), axis=1))
    #test_accuracy = (test_target_torch.detach().numpy() == test_pred).float().mean().detach().numpy()
    test_accuracy = (test_target_torch.detach().numpy() == test_pred).mean()

    #test_rmse = ((test_pred-test_target_torch)**2).mean().sqrt().detach().numpy()
    test_rmse = (np.sqrt((test_pred-test_target_torch.detach().numpy())**2).mean())

    return test_accuracy, test_rmse

for i in range(1):
    #pred = net(train_data_torch)
    #loss = criterion(pred, train_target_torch)
    
    #optimizer.zero_grad()
    #loss.backward()
    #optimizer.step()
    
    if i % 100 == 0:
        #train_accuracy, train_rmse = validate(net, features_temp, labels_temp)
        test_accuracy, test_rmse = validate(net, features_test, labels_test, i)
        #print(f'Epoch = {i} loss={loss} train_acc = {train_accuracy:.3f} test_acc = {test_accuracy:.3f} train_rmse = {train_rmse:.3f}  test_rmse = {test_rmse:.3f}')         
        print(f'Epoch = {i} test_acc = {test_accuracy:.3f}  test_rmse = {test_rmse:.3f}') 

[[ 1.  4.  0.  2.]
 [ 2.  4.  1.  2.]
 [ 4.  4.  3.  2.]
 [ 5.  3.  5.  2.]
 [ 8.  2.  8.  2.]
 [ 9.  2.  9.  2.]
 [10.  2. 10.  2.]
 [11.  2. 11.  2.]
 [11.  2. 12.  2.]
 [12.  2. 13.  2.]
 [13.  2. 14.  2.]
 [14.  2. 15.  2.]
 [15.  2. 16.  2.]
 [16.  2. 17.  2.]
 [ 3.  2.  3.  2.]
 [ 5.  3.  5.  2.]
 [ 8.  3.  8.  2.]
 [ 9.  3.  9.  2.]
 [10.  3. 10.  2.]
 [10.  3. 11.  2.]
 [11.  3. 12.  2.]
 [12.  3. 13.  2.]
 [13.  3. 14.  2.]
 [14.  3. 15.  2.]
 [15.  3. 16.  2.]
 [16.  3. 17.  2.]
 [ 3.  3.  3.  2.]
 [ 5.  3.  5.  2.]
 [ 8.  3.  8.  2.]
 [ 9.  3.  9.  2.]
 [10.  3. 10.  2.]
 [10.  3. 11.  2.]
 [11.  3. 12.  2.]
 [12.  3. 13.  2.]
 [13.  3. 14.  2.]
 [14.  3. 15.  2.]
 [15.  3. 16.  2.]
 [16.  3. 17.  2.]
 [ 3.  3.  3.  2.]
 [ 5.  3.  5.  2.]
 [ 8.  3.  8.  2.]
 [ 9.  3.  9.  2.]
 [10.  3. 10.  2.]
 [11.  3. 11.  2.]
 [11.  3. 12.  2.]
 [12.  3. 13.  2.]
 [13.  3. 14.  2.]
 [14.  3. 15.  2.]
 [15.  3. 16.  2.]
 [16.  3. 17.  2.]
 [ 3.  3.  3.  2.]
 [ 5.  3.  5.  2.]
 [ 8.  3.  8

/tmp/ipykernel_109417/3030192740.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  train_target_torch = torch.tensor(torch.from_numpy(np.array(labels_temp)).float())
/tmp/ipykernel_109417/3030192740.py:16: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  test_target_torch = torch.tensor(torch.from_numpy(np.array(test_target)).float())


In [23]:
preds = net(torch.from_numpy(features_test[3]).float()).detach().numpy()
print(np.rint(preds))

[5. 3.]


In [67]:
for p in preds:
    print(p)

tensor(4.9992, grad_fn=<UnbindBackward0>)
tensor(2.0004, grad_fn=<UnbindBackward0>)


In [60]:
labels_test[3]

array([5, 2], dtype=uint8)